(******************************************************************************)
(* Copyright (c) 2020 Steven Keuchel, Dominique Devriese, Sander Huyghebaert  *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(* Redistribution and use in source and binary forms, with or without         *)
(* modification, are permitted provided that the following conditions are     *)
(* met:                                                                       *)
(*                                                                            *)
(* 1. Redistributions of source code must retain the above copyright notice,  *)
(*    this list of conditions and this disclaimer.                            *)
(*                                                                            *)
(* 2. Redistributions in binary form must reproduce the above copyright       *)
(*    notice, this list of conditions and the following disclaimer in the     *)
(*    documentation and/or other materials provided with the distribution.    *)
(*                                                                            *)
(* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        *)
(* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED  *)
(* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR *)
(* PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR          *)
(* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,      *)
(* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,        *)
(* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR         *)
(* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF     *)
(* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING       *)
(* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         *)
(* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               *)
(******************************************************************************)

(* ========================================================================= *)
(* Example/BearSSLCheckScalar.v — BearSSL P-256 `check_scalar`, compare step.*)
(*                                                                           *)
(* Target 3 of 3 from the "Breaking Bad" BearSSL disclosure (Schneider et    *)
(* al., ASIA CCS'25, arXiv:2410.13489, appendix A.5.4 / Table 12).           *)
(*                                                                           *)
(* The instruction list and reg spec definitions below are                   *)
(* STATEMENT-RELEVANT: the noninterference theorem in                        *)
(* BearSSLCheckScalarResult.v references them by name.  The contract and     *)
(* valid_* VC proof are not.                                                 *)
(* ========================================================================= *)

From Katamaran Require Import RiscvPmp.CFGVer.Example.Prelude.

(* ------------------------------------------------------------------------ *)
(* ORIGINAL C — BearSSL src/ec/ec_p256_m62.c:1610 (commit 79c060e).          *)
(* Checks that the secret scalar k is nonzero and below the curve order, by  *)
(* comparing it to P256_N byte by byte in constant time:                     *)
(*                                                                           *)
(*     static uint32_t                                                       *)
(*     check_scalar(const unsigned char *k, size_t klen)                     *)
(*     {                                                                     *)
(*         uint32_t z;                                                       *)
(*         int32_t c;                                                        *)
(*         size_t u;                                                         *)
(*                                                                           *)
(*         if (klen > 32) {                                                  *)
(*             return 0;                                                     *)
(*         }                                                                 *)
(*         z = 0;                                                            *)
(*         for (u = 0; u < klen; u ++) {                                     *)
(*             z |= k[u];                                                    *)
(*         }                                                                 *)
(*         if (klen == 32) {                                                 *)
(*             c = 0;                                                        *)
(*             for (u = 0; u < klen; u ++) {                                 *)
(*                 c |= -(int32_t)EQ0(c) & CMP(k[u], P256_N[u]);   <-- here  *)
(*             }                                                             *)
(*         } else {                                                          *)
(*             c = -1;                                                       *)
(*         }                                                                 *)
(*         return NEQ(z, 0) & LT0(c);                                        *)
(*     }                                                                     *)
(*                                                                           *)
(* with, from src/inner.h:                                                   *)
(*                                                                           *)
(*     static inline uint32_t GT(uint32_t x, uint32_t y) {                   *)
(*         uint32_t z = y - x;                                               *)
(*         return (z ^ ((x ^ y) & (x ^ z))) >> 31;                           *)
(*     }                                                                     *)
(*     static inline int32_t CMP(uint32_t x, uint32_t y) {                   *)
(*         return (int32_t)GT(x, y) | -(int32_t)GT(y, x);                    *)
(*     }                                                                     *)
(*     static inline uint32_t EQ0(int32_t x) {                               *)
(*         uint32_t q = (uint32_t)x;                                         *)
(*         return ~(q | -q) >> 31;                                           *)
(*     }                                                                     *)
(*                                                                           *)
(* The paper (Table 12, appendix A.5.4) reports LLVM 12–15 on riscv64 and    *)
(* x86-i386 replacing this bitmask arithmetic with a secret-dependent BRANCH *)
(* (the finding is for the i62/i64 P-256 implementations, i.e. 64-bit).      *)
(*                                                                           *)
(* On the RV32I configuration this case study targets, clang 18.1.3          *)
(* --target=riscv32 -march=rv32i -mabi=ilp32 emits branch-free code at every *)
(* -O level we tried: at -O2 the whole 32-iteration loop compiles with a     *)
(* single `bne` on the PUBLIC loop counter and no secret-dependent branch at *)
(* all.  So on 32-bit RISC-V this is already a correct implementation.       *)
(*                                                                           *)
(* Verified here is the loop BODY — the comparison step that carries the     *)
(* whole bitmask idiom, and the granularity of the paper's own minimal       *)
(* reproducer:                                                               *)
(*                                                                           *)
(*     int32_t check_scalar_step(int32_t c, uint32_t ku, uint32_t nu) {      *)
(*         return c | (-(int32_t)EQ0(c) & CMP(ku, nu));                      *)
(*     }                                                                     *)
(*                                                                           *)
(* clang 18.1.3 --target=riscv32 -march=rv32i -mabi=ilp32 -O2 gives the      *)
(* 16-instruction branch-free listing below — note it inlines BOTH GT calls  *)
(* of CMP, which is why the same `xor a4, a2, a1` feeds two mask chains.     *)
(* Argument registers per the RISC-V calling convention: A0 = c, A1 = ku,    *)
(* A2 = nu; A3-A5 are compiler-chosen scratch; the result returns in A0.     *)
(* Translated with tools/asm_to_ast.py; trailing `ret` dropped as usual.     *)
(* ------------------------------------------------------------------------ *)
Definition check_scalar_instrs : list AST :=
  [ RTYPE A1 A2 A3 RISCV_SUB                (* sub   a3, a2, a1 *)
  ; RTYPE A1 A2 A4 RISCV_XOR                (* xor   a4, a2, a1 *)
  ; RTYPE A1 A3 A5 RISCV_XOR                (* xor   a5, a3, a1 *)
  ; RTYPE A4 A5 A5 RISCV_AND                (* and   a5, a5, a4 *)
  ; RTYPE A3 A5 A3 RISCV_XOR                (* xor   a3, a5, a3 *)
  ; SHIFTIOP (bv.of_Z 31) A3 A3 RISCV_SRLI  (* srli  a3, a3, 31 *)
  ; RTYPE A2 A1 A1 RISCV_SUB                (* sub   a1, a1, a2 *)
  ; RTYPE A2 A1 A2 RISCV_XOR                (* xor   a2, a1, a2 *)
  ; RTYPE A4 A2 A2 RISCV_AND                (* and   a2, a2, a4 *)
  ; RTYPE A1 A2 A1 RISCV_XOR                (* xor   a1, a2, a1 *)
  ; SHIFTIOP (bv.of_Z 31) A1 A1 RISCV_SRAI  (* srai  a1, a1, 31 *)
  ; RTYPE A1 A3 A1 RISCV_OR                 (* or    a1, a3, a1 *)
  ; RTYPE A0 X0 A2 RISCV_SLTU               (* snez  a2, a0 *)
  ; ITYPE (bv.of_Z (-1)) A2 A2 RISCV_ADDI   (* addi  a2, a2, -1 *)
  ; RTYPE A1 A2 A1 RISCV_AND                (* and   a1, a2, a1 *)
  ; RTYPE A0 A1 A0 RISCV_OR                 (* or    a0, a1, a0 *)
  ].

(* All inputs SECRET.  In the real function A2 (= P256_N[u]) is a PUBLIC curve
   constant and only A0/A1 carry secrets; declaring it private too is strictly
   stronger and costs nothing here, since the code is branch-free.  Scratch
   registers A3-A5 are private as usual.  Register-only, so mem_specs is []. *)
Definition check_scalar_reg_specs : list reg_spec :=
  [(A0, false, None); (A1, false, None); (A2, false, None);
   (A3, false, None); (A4, false, None); (A5, false, None)].

(* Base-parametric contract (Σ = ["p"]): arbitrary 4-aligned load address.
   Fuel 24 comfortably exceeds the 16 instruction steps plus the exit step. *)
Definition check_scalar_cfg_contract_param (ia : N) : @CFGVerifierContract ["p" :: ty_xlenbits] :=
  gen_contract_param ia check_scalar_reg_specs [] check_scalar_instrs []
    (pcOutOfInstrs_exitCond ia check_scalar_instrs) 24.

Lemma valid_check_scalar_cfg_contract_param (ia : N) :
  ValidCFGVerifierContract (check_scalar_cfg_contract_param ia).
Proof. intros; vm_compute; solve_vc; solve_symbase_fetch. Qed.
