(******************************************************************************)
(* Copyright (c) 2020 Steven Keuchel, Dominique Devriese, Sander Huyghebaert  *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(* Redistribution and use in source and binary forms, with or without         *)
(* modification, are permitted provided that the following conditions are     *)
(* met:                                                                       *)
(*                                                                            *)
(* 1. Redistributions of source code must retain the above copyright notice,  *)
(*    this list of conditions and the following disclaimer.                   *)
(*                                                                            *)
(* 2. Redistributions in binary form must reproduce the above copyright       *)
(*    notice, this list of conditions and the following disclaimer in the     *)
(*    documentation and/or other materials provided with the distribution.    *)
(*                                                                            *)
(* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        *)
(* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED  *)
(* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR *)
(* PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR          *)
(* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,      *)
(* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,        *)
(* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR         *)
(* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF     *)
(* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING       *)
(* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         *)
(* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               *)
(******************************************************************************)

(* ========================================================================= *)
(* Example/BearSSLMuladd.v — BearSSL `br_i31_muladd_small`, quotient step.   *)
(*                                                                           *)
(* Target 2 of 3 from the "Breaking Bad" BearSSL disclosure (Schneider et    *)
(* al., ASIA CCS'25, arXiv:2410.13489, appendix A.5.3 / Table 11).           *)
(*                                                                           *)
(* The instruction list and reg spec definitions below are                   *)
(* STATEMENT-RELEVANT: the noninterference theorem in BearSSLMuladdResult.v  *)
(* references them by name.  The contract and valid_* VC proof are not.      *)
(* ========================================================================= *)

From Katamaran Require Import RiscvPmp.CFGVer.Example.Prelude.

(* ------------------------------------------------------------------------ *)
(* ORIGINAL C — BearSSL src/int/i31_muladd.c (commit 79c060e, the revision   *)
(* analysed by the paper).  `br_i31_muladd_small` computes x <- (x*2^31+z)   *)
(* mod m.  It estimates the quotient q with a 64/32 division on the top      *)
(* words and then corrects it.  The correction is the constant-time select   *)
(* below, and it is the part the compiler breaks:                            *)
(*                                                                           *)
(*     g = br_div(a0 >> 1, a1 | (a0 << 31), b0);                             *)
(*     q = MUX(EQ(a0, b0), 0x7FFFFFFF, MUX(EQ(g, 0), 0, g - 1));             *)
(*                                                                           *)
(* with, from src/inner.h:                                                   *)
(*                                                                           *)
(*     static inline uint32_t NOT(uint32_t ctl) { return ctl ^ 1; }          *)
(*     static inline uint32_t MUX(uint32_t ctl, uint32_t x, uint32_t y) {    *)
(*         return y ^ (-ctl & (x ^ y));                                      *)
(*     }                                                                     *)
(*     static inline uint32_t EQ(uint32_t x, uint32_t y) {                   *)
(*         uint32_t q = x ^ y;                                               *)
(*         return NOT((q | -q) >> 31);                                       *)
(*     }                                                                     *)
(*                                                                           *)
(* The paper (Table 11) reports LLVM 13/14/15 on riscv64 and x86-i386 at     *)
(* -O1/-O2/-O3/-Ofast turning this bitmask select into a secret-dependent    *)
(* BRANCH.  We reproduce this on the exact configuration this case study     *)
(* targets — clang 18.1.3, --target=riscv32 -march=rv32i -mabi=ilp32 -O2:    *)
(*                                                                           *)
(*     muladd_q:                                                             *)
(*         bne   a0, a1, .LBB0_2      <-- BRANCH ON SECRET (a0 == b0)        *)
(*         lui   a0, 524288                                                  *)
(*         addi  a0, a0, -1                                                  *)
(*         ret                                                               *)
(*     .LBB0_2:                                                              *)
(*         snez  a0, a2                                                      *)
(*         ...                                                               *)
(*                                                                           *)
(* so the finding still stands on a current LLVM and on 32-bit RISC-V.  That *)
(* binary is NOT what we verify here: `bne` on a secret is exactly the leak, *)
(* and the CFG verifier rejects it (see BearSSLMuladdResult.v for the        *)
(* negative result).                                                         *)
(*                                                                           *)
(* THE CORRECT IMPLEMENTATION verified below applies the standard fix — an   *)
(* empty inline-asm optimisation barrier on the mask, which stops LLVM's     *)
(* InstCombine pass from re-forming a `select` out of the bitmask arithmetic *)
(* — while keeping full -O2 optimisation everywhere else:                    *)
(*                                                                           *)
(*     static inline uint32_t opaque(uint32_t v) {                           *)
(*         __asm__ ("" : "+r"(v)); return v;                                 *)
(*     }                                                                     *)
(*     uint32_t muladd_q_fix(uint32_t a0, uint32_t b0, uint32_t g) {         *)
(*         return MUX(opaque(EQ(a0, b0)), 0x7FFFFFFF,                        *)
(*                    MUX(opaque(EQ(g, 0)), 0, g - 1));                      *)
(*     }                                                                     *)
(*                                                                           *)
(* clang 18.1.3 --target=riscv32 -march=rv32i -mabi=ilp32 -O2 emits the      *)
(* 12-instruction branch-free listing transcribed below (the two `#APP` /    *)
(* `#NO_APP` markers of the empty asm block emit no instruction).  Argument  *)
(* registers per the RISC-V calling convention: A0 = a0, A1 = b0, A2 = g;    *)
(* the result is returned in A0.                                             *)
(*                                                                           *)
(* Translated with tools/asm_to_ast.py; each entry carries its source line.  *)
(* The trailing `ret` is deliberately dropped (its target is the symbolic    *)
(* link register), exactly as in Cmovznz4 — the pcOutOfInstrs exit condition *)
(* fires once pc has advanced past the last real instruction.                *)
(* ------------------------------------------------------------------------ *)
Definition muladd_q_instrs : list AST :=
  [ RTYPE A1 A0 A0 RISCV_XOR                (* xor   a0, a0, a1 *)
  ; ITYPE (bv.of_Z 1) A0 A0 RISCV_SLTIU     (* seqz  a0, a0 *)
  ; ITYPE (bv.of_Z 1) A2 A1 RISCV_SLTIU     (* seqz  a1, a2 *)
  ; ITYPE (bv.of_Z (-1)) A2 A2 RISCV_ADDI   (* addi  a2, a2, -1 *)
  ; ITYPE (bv.of_Z (-1)) A1 A1 RISCV_ADDI   (* addi  a1, a1, -1 *)
  ; RTYPE A2 A1 A1 RISCV_AND                (* and   a1, a1, a2 *)
  ; RTYPE A0 X0 A0 RISCV_SUB                (* neg   a0, a0 *)
  ; UTYPE (bv.of_Z 524288) A2 RISCV_LUI     (* lui   a2, 524288 *)
  ; ITYPE (bv.of_Z (-1)) A2 A2 RISCV_ADDI   (* addi  a2, a2, -1 *)
  ; RTYPE A2 A1 A2 RISCV_XOR                (* xor   a2, a1, a2 *)
  ; RTYPE A0 A2 A0 RISCV_AND                (* and   a0, a2, a0 *)
  ; RTYPE A1 A0 A0 RISCV_XOR                (* xor   a0, a0, a1 *)
  ].

(* All three inputs are SECRET (is_public = false, no pinned value): a0, b0
   and g range over arbitrary, independent values in the two worlds.  This is
   the strongest statement available here — the theorem says the observable
   trace is identical no matter how the three 31-bit words differ.  The
   program is register-only (no loads/stores at all), so mem_specs is []. *)
Definition muladd_q_reg_specs : list reg_spec :=
  [(A0, false, None); (A1, false, None); (A2, false, None)].

(* Base-parametric contract (Σ = ["p"]): verified for an ARBITRARY 4-aligned
   load address, following the Phase 4.2 pattern used by every other example.
   Fuel 20 comfortably exceeds the 12 instruction steps plus the exit step. *)
Definition muladd_q_cfg_contract_param (ia : N) : @CFGVerifierContract ["p" :: ty_xlenbits] :=
  gen_contract_param ia muladd_q_reg_specs muladd_q_instrs []
    (pcOutOfInstrs_exitCond ia muladd_q_instrs) 20.

Lemma valid_muladd_q_cfg_contract_param (ia : N) :
  ValidCFGVerifierContract (muladd_q_cfg_contract_param ia).
Proof. intros; vm_compute; solve_vc; solve_symbase_fetch. Qed.
