(******************************************************************************)
(* Copyright (c) 2020 Steven Keuchel, Dominique Devriese, Sander Huyghebaert  *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(* Redistribution and use in source and binary forms, with or without         *)
(* modification, are permitted provided that the following conditions are     *)
(* met:                                                                       *)
(*                                                                            *)
(* 1. Redistributions of source code must retain the above copyright notice,  *)
(*    this list of conditions and this disclaimer.                            *)
(*                                                                            *)
(* 2. Redistributions in binary form must reproduce the above copyright       *)
(*    notice, this list of conditions and the following disclaimer in the     *)
(*    documentation and/or other materials provided with the distribution.    *)
(*                                                                            *)
(* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS        *)
(* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED  *)
(* TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR *)
(* PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR          *)
(* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,      *)
(* EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,        *)
(* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR         *)
(* PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF     *)
(* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING       *)
(* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         *)
(* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.               *)
(******************************************************************************)

(* ========================================================================= *)
(* Example/BearSSLModpow.v — BearSSL `modpow_opt`, window-lookup step.       *)
(*                                                                           *)
(* Target 1 of 3 from the "Breaking Bad" BearSSL disclosure (Schneider et    *)
(* al., ASIA CCS'25, arXiv:2410.13489, appendix A.5.2 / Table 10).           *)
(*                                                                           *)
(* The instruction list and reg spec definitions below are                   *)
(* STATEMENT-RELEVANT: the noninterference theorem in BearSSLModpowResult.v  *)
(* references them by name.  The contract and valid_* VC proof are not.      *)
(* ========================================================================= *)

From Katamaran Require Import RiscvPmp.CFGVer.Example.Prelude.

(* ------------------------------------------------------------------------ *)
(* ORIGINAL C — BearSSL src/int/i31_modpow2.c (commit 79c060e), inside       *)
(* `br_i31_modpow_opt`.  The exponent window is looked up in constant time   *)
(* by OR-ing in each candidate under a mask derived from EQ:                 *)
(*                                                                           *)
(*     if (win_len > 1) {                                                    *)
(*         br_i31_zero(t2, m[0]);                                            *)
(*         base = t2 + mwlen;                                                *)
(*         for (u = 1; u < ((uint32_t)1 << k); u ++) {                       *)
(*             uint32_t mask;                                                *)
(*                                                                           *)
(*             mask = -EQ(u, bits);                       <-- the mask       *)
(*             for (v = 1; v < mwlen; v ++) {                                *)
(*                 t2[v] |= mask & base[v];               <-- the select     *)
(*             }                                                             *)
(*             base += mwlen;                                                *)
(*         }                                                                 *)
(*     }                                                                     *)
(*                                                                           *)
(* with EQ/NOT from src/inner.h (see BearSSLMuladd.v for their bodies).      *)
(* `bits` is the secret exponent window; `u` is the public loop index.       *)
(*                                                                           *)
(* The paper (Table 10) reports LLVM 13/14/15 on x86-64, x86-i386, aarch64   *)
(* and armv7 replacing this mask with a `cmov`/`csel` that computes an       *)
(* ADDRESS, turning the select into a secret-dependent MEMORY ACCESS         *)
(* (appendix A.5.2: "in i31 the compiler uses a branch to jump over the      *)
(* assignment").  Note the paper's Table 10 does NOT list riscv64 for this   *)
(* function, and indeed clang 18.1.3 --target=riscv32 -march=rv32i           *)
(* -mabi=ilp32 emits branch-free code at every -O level we tried             *)
(* (-O0/-O1/-O2/-Os) — so on the configuration this case study targets this  *)
(* one is a CORRECT implementation as the compiler produces it, with no fix  *)
(* needed.  That is itself worth recording: the leak is architecture- and    *)
(* compiler-specific, and verifying the actual RV32I binary is what settles  *)
(* it.                                                                       *)
(*                                                                           *)
(* This is the loop BODY (one v-iteration), which is the granularity of the  *)
(* paper's own minimal reproducer:                                           *)
(*                                                                           *)
(*     uint32_t modpow_win_step(uint32_t t2v, uint32_t basev,                *)
(*                              uint32_t u, uint32_t bits) {                 *)
(*         uint32_t mask = -EQ(u, bits);                                     *)
(*         return t2v | (mask & basev);                                      *)
(*     }                                                                     *)
(*                                                                           *)
(* clang 18.1.3 --target=riscv32 -march=rv32i -mabi=ilp32 -O2 gives the      *)
(* 5-instruction branch-free listing below.  Argument registers per the      *)
(* RISC-V calling convention: A0 = t2v, A1 = basev, A2 = u, A3 = bits;       *)
(* the result is returned in A0.  Translated with tools/asm_to_ast.py; the   *)
(* trailing `ret` is dropped as in every other example.                      *)
(* ------------------------------------------------------------------------ *)
Definition modpow_win_instrs : list AST :=
  [ RTYPE A3 A2 A2 RISCV_XOR                (* xor   a2, a2, a3 *)
  ; RTYPE A2 X0 A2 RISCV_SLTU               (* snez  a2, a2 *)
  ; ITYPE (bv.of_Z (-1)) A2 A2 RISCV_ADDI   (* addi  a2, a2, -1 *)
  ; RTYPE A1 A2 A1 RISCV_AND                (* and   a1, a2, a1 *)
  ; RTYPE A0 A1 A0 RISCV_OR                 (* or    a0, a1, a0 *)
  ].

(* All four inputs SECRET.  In the real loop `u` is a public index, but
   leaving it private only strengthens the theorem — we prove the trace is
   independent of ALL of t2v, basev, u and bits.  Register-only: no loads or
   stores, so mem_specs is []. *)
Definition modpow_win_reg_specs : list reg_spec :=
  [(A0, false, None); (A1, false, None); (A2, false, None); (A3, false, None)].

(* Base-parametric contract (Σ = ["p"]): arbitrary 4-aligned load address.
   Fuel 12 comfortably exceeds the 5 instruction steps plus the exit step. *)
Definition modpow_win_cfg_contract_param (ia : N) : @CFGVerifierContract ["p" :: ty_xlenbits] :=
  gen_contract_param ia modpow_win_reg_specs [] modpow_win_instrs []
    (pcOutOfInstrs_exitCond ia modpow_win_instrs) 12.

Lemma valid_modpow_win_cfg_contract_param (ia : N) :
  ValidCFGVerifierContract (modpow_win_cfg_contract_param ia).
Proof. intros; vm_compute; solve_vc; solve_symbase_fetch. Qed.
