(* ========================================================================= *)
(* Example/ZZMuladdFullN4.v -- THROWAWAY, PLAN-muladd-full.md Phase 2/3.      *)
(*                                                                           *)
(* Same whole-function BearSSL `br_i31_muladd_small` build as               *)
(* ZZMuladdFullN2.v (see that file's header for the full three-deviation     *)
(* disclosure: hardening barriers, the word-copy memmove replacement, and    *)
(* the post-compile division-loop trip-count patch) -- this is the second   *)
(* data point, mlen=4 instead of mlen=2, for the doubling-ratio measurement. *)
(*                                                                           *)
(* Loop-count patch here: `li <reg>, 32` -> `li <reg>, 5` (4 real            *)
(* iterations) at the same two sites.                                       *)
(*                                                                           *)
(* Memory layout (code identical size -- same 282 instructions, only two     *)
(* immediate operands differ from ZZMuladdFullN2.v, so the byte layout is    *)
(* offset-for-offset identical up to the array sizes below):                 *)
(*   code   : p+0    .. p+1127  (282 instrs * 4 bytes = 1128 bytes)          *)
(*   x[]    : p+1128 .. p+1147  (5 words: x[0]=bitlen PINNED 127 (PUBLIC);   *)
(*            x[1..4] SECRET)                                                *)
(*   m[]    : p+1148 .. p+1167  (5 words: m[0]=bitlen PINNED 127 (PUBLIC);   *)
(*            m[1..4] PUBLIC-but-unpinned)                                   *)
(*   stack  : p+1168 .. p+1183  (4 words: S0-S3 spill slots)                 *)
(*   A0=&x[0]=p+1128, A2=&m[0]=p+1148, X2(sp)=p+1184. Bound 1184.            *)
(*                                                                           *)
(* m[0]=x[0]=127 gives mlen=(127+31)>>5=4 (muladd's own accumulate loop),    *)
(* AND (127+63)>>5=5 (so add/sub's own `u<5` loop runs u=1,2,3,4 -- also 4   *)
(* trips) -- same cross-check as the N=2 file. mblr=127&31=31<>0, same       *)
(* shift-extraction ELSE branch as N=2.                                      *)
(* ------------------------------------------------------------------------ *)

From Katamaran Require Export RiscvPmp.CFGVer.Example.Prelude.

Definition S0 : RegIdx := bv.of_nat 8.
Definition S1 : RegIdx := bv.of_nat 9.
Definition S2 : RegIdx := bv.of_nat 18.
Definition S3 : RegIdx := bv.of_nat 19.

Definition zzmuladdfulln4_instrs : list AST :=
  [ LOAD (bv.of_Z 0) A2 T0 false WORD   (* lw	T0, 0(A2) *)
  ; BTYPE (bv.of_Z 212) X0 T0 RISCV_BEQ   (* beqz	T0, .LBB3_5 *)
  ; ITYPE (bv.of_Z 31) X0 A3 RISCV_ADDI   (* li	A3, 31 *)
  ; BTYPE (bv.of_Z 208) T0 A3 RISCV_BLTU   (* bltu	A3, T0, .LBB3_6 *)
  ; LOAD (bv.of_Z 4) A0 A3 false WORD   (* lw	A3, 4(A0) *)
  ; LOAD (bv.of_Z 4) A2 A2 false WORD   (* lw	A2, 4(A2) *)
  ; SHIFTIOP (bv.of_Z 1) A3 A4 RISCV_SRLI   (* srli	A4, A3, 1 *)
  ; SHIFTIOP (bv.of_Z 31) A3 A3 RISCV_SLLI   (* slli	A3, A3, 31 *)
  ; RTYPE A1 A3 A1 RISCV_OR   (* or	A1, A3, A1 *)
  ; RTYPE A2 A4 A3 RISCV_XOR   (* xor	A3, A4, A2 *)
  ; ITYPE (bv.of_Z 1) A3 A3 RISCV_SLTIU   (* seqz	A3, A3 *)
  ; ITYPE (bv.of_Z (-1)) A3 A3 RISCV_ADDI   (* addi	A3, A3, -1 *)
  ; RTYPE A4 A3 A3 RISCV_AND   (* and	A3, A3, A4 *)
  ; ITYPE (bv.of_Z 5) X0 A4 RISCV_ADDI   (* li	A4, 5 *)
  ; ITYPE (bv.of_Z 1) X0 A5 RISCV_ADDI   (* li	A5, 1 *)
  ; ITYPE (bv.of_Z 1) X0 A6 RISCV_ADDI   (* li	A6, 1 *)
  ; ITYPE (bv.of_Z (-1)) A4 A4 RISCV_ADDI   (* addi	A4, A4, -1 *)
  ; RTYPE A6 A3 A7 RISCV_SLL   (* sll	A7, A3, A6 *)
  ; RTYPE A4 A1 T0 RISCV_SRL   (* srl	T0, A1, A4 *)
  ; RTYPE T0 A7 A7 RISCV_OR   (* or	A7, A7, T0 *)
  ; RTYPE A2 A7 T0 RISCV_SUB   (* sub	T0, A7, A2 *)
  ; RTYPE A2 A7 A7 RISCV_XOR   (* xor	A7, A7, A2 *)
  ; RTYPE A2 T0 T1 RISCV_XOR   (* xor	T1, T0, A2 *)
  ; RTYPE A7 T1 A7 RISCV_AND   (* and	A7, T1, A7 *)
  ; RTYPE T0 A7 A7 RISCV_XOR   (* xor	A7, A7, T0 *)
  ; ITYPE (bv.of_Z (-1)) A7 A7 RISCV_XORI   (* not	A7, A7 *)
  ; SHIFTIOP (bv.of_Z 31) A7 A7 RISCV_SRLI   (* srli	A7, A7, 31 *)
  ; RTYPE A4 A3 T1 RISCV_SRL   (* srl	T1, A3, A4 *)
  ; RTYPE A7 T1 A7 RISCV_OR   (* or	A7, T1, A7 *)
  ; RTYPE A6 T0 T0 RISCV_SRL   (* srl	T0, T0, A6 *)
  ; RTYPE A4 A2 T1 RISCV_SLL   (* sll	T1, A2, A4 *)
  ; RTYPE T1 A1 T1 RISCV_SUB   (* sub	T1, A1, T1 *)
  ; RTYPE A7 X0 A7 RISCV_SUB   (* neg	A7, A7 *)
  ; RTYPE A3 T0 T0 RISCV_XOR   (* xor	T0, T0, A3 *)
  ; RTYPE A7 T0 T0 RISCV_AND   (* and	T0, T0, A7 *)
  ; RTYPE A3 T0 A3 RISCV_XOR   (* xor	A3, T0, A3 *)
  ; RTYPE A1 T1 T0 RISCV_XOR   (* xor	T0, T1, A1 *)
  ; RTYPE A7 T0 A7 RISCV_AND   (* and	A7, T0, A7 *)
  ; RTYPE A1 A7 A1 RISCV_XOR   (* xor	A1, A7, A1 *)
  ; ITYPE (bv.of_Z 1) A6 A6 RISCV_ADDI   (* addi	A6, A6, 1 *)
  ; BTYPE (bv.of_Z (-96)) A4 A5 RISCV_BLTU   (* bltu	A5, A4, .LBB3_3 *)
  ; RTYPE A2 A1 A4 RISCV_SUB   (* sub	A4, A1, A2 *)
  ; RTYPE A2 A1 A5 RISCV_XOR   (* xor	A5, A1, A2 *)
  ; RTYPE A2 A4 A2 RISCV_XOR   (* xor	A2, A4, A2 *)
  ; RTYPE A5 A2 A2 RISCV_AND   (* and	A2, A2, A5 *)
  ; RTYPE A4 A2 A2 RISCV_XOR   (* xor	A2, A2, A4 *)
  ; ITYPE (bv.of_Z (-1)) A2 A2 RISCV_XORI   (* not	A2, A2 *)
  ; SHIFTIOP (bv.of_Z 31) A2 A2 RISCV_SRLI   (* srli	A2, A2, 31 *)
  ; RTYPE A2 A3 A2 RISCV_OR   (* or	A2, A3, A2 *)
  ; RTYPE A2 X0 A2 RISCV_SUB   (* neg	A2, A2 *)
  ; RTYPE A1 A4 A4 RISCV_XOR   (* xor	A4, A4, A1 *)
  ; RTYPE A2 A4 A2 RISCV_AND   (* and	A2, A4, A2 *)
  ; RTYPE A1 A2 A1 RISCV_XOR   (* xor	A1, A2, A1 *)
  ; STORE (bv.of_Z 4) A1 A0 WORD   (* sw	A1, 4(A0) *)
  ; RISCV_JALR (bv.of_Z 0) X1 X0   (* ret *)
  ; ITYPE (bv.of_Z (-16)) X2 X2 RISCV_ADDI   (* addi	X2, X2, -16 *)
  ; STORE (bv.of_Z 12) S0 X2 WORD   (* sw	S0, 12(X2)                      # 4-byte Folded Spill *)
  ; STORE (bv.of_Z 8) S1 X2 WORD   (* sw	S1, 8(X2)                       # 4-byte Folded Spill *)
  ; STORE (bv.of_Z 4) S2 X2 WORD   (* sw	S2, 4(X2)                       # 4-byte Folded Spill *)
  ; STORE (bv.of_Z 0) S3 X2 WORD   (* sw	S3, 0(X2)                       # 4-byte Folded Spill *)
  ; UTYPE (bv.of_Z 524288) A3 RISCV_LUI   (* lui	A3, 524288 *)
  ; ITYPE (bv.of_Z (-1)) A3 A3 RISCV_ADDI   (* addi	A3, A3, -1 *)
  ; ITYPE (bv.of_Z 31) T0 A6 RISCV_ADDI   (* addi	A6, T0, 31 *)
  ; SHIFTIOP (bv.of_Z 5) A6 T1 RISCV_SRLI   (* srli	T1, A6, 5 *)
  ; SHIFTIOP (bv.of_Z 2) T1 A5 RISCV_SLLI   (* slli	A5, T1, 2 *)
  ; RTYPE A5 A0 A7 RISCV_ADD   (* add	A7, A0, A5 *)
  ; LOAD (bv.of_Z 0) A7 A4 false WORD   (* lw	A4, 0(A7) *)
  ; UTYPE (bv.of_Z 262144) T5 RISCV_LUI   (* lui	T5, 262144 *)
  ; ITYPE (bv.of_Z 31) T0 T0 RISCV_ANDI   (* andi	T0, T0, 31 *)
  ; ITYPE (bv.of_Z (-1)) T5 T5 RISCV_ADDI   (* addi	T5, T5, -1 *)
  ; BTYPE (bv.of_Z 148) X0 T0 RISCV_BEQ   (* beqz	T0, .LBB3_11 *)
  ; ITYPE (bv.of_Z (-1)) T1 T6 RISCV_ADDI   (* addi	T6, T1, -1 *)
  ; SHIFTIOP (bv.of_Z 2) T6 T2 RISCV_SLLI   (* slli	T2, T6, 2 *)
  ; RTYPE T2 A0 T3 RISCV_ADD   (* add	T3, A0, T2 *)
  ; LOAD (bv.of_Z 0) T3 T4 false WORD   (* lw	T4, 0(T3) *)
  ; ITYPE (bv.of_Z 31) T0 T1 RISCV_XORI   (* xori	T1, T0, 31 *)
  ; RTYPE T1 A4 S0 RISCV_SLL   (* sll	S0, A4, T1 *)
  ; RTYPE T0 T4 T4 RISCV_SRL   (* srl	T4, T4, T0 *)
  ; RTYPE T5 T6 T6 RISCV_AND   (* and	T6, T6, T5 *)
  ; RTYPE A3 S0 T5 RISCV_AND   (* and	T5, S0, A3 *)
  ; BTYPE (bv.of_Z 40) X0 T6 RISCV_BEQ   (* beqz	T6, .LBB3_10 *)
  ; SHIFTIOP (bv.of_Z 2) T6 S0 RISCV_SLLI   (* slli	S0, T6, 2 *)
  ; RTYPE A0 S0 S0 RISCV_ADD   (* add	S0, S0, A0 *)
  ; ITYPE (bv.of_Z 4) S0 S0 RISCV_ADDI   (* addi	S0, S0, 4 *)
  ; LOAD (bv.of_Z (-4)) S0 S1 false WORD   (* lw	S1, -4(S0) *)
  ; ITYPE (bv.of_Z (-1)) T6 T6 RISCV_ADDI   (* addi	T6, T6, -1 *)
  ; ITYPE (bv.of_Z (-4)) S0 S2 RISCV_ADDI   (* addi	S2, S0, -4 *)
  ; STORE (bv.of_Z 0) S1 S0 WORD   (* sw	S1, 0(S0) *)
  ; ITYPE (bv.of_Z 0) S2 S0 RISCV_ADDI   (* mv	S0, S2 *)
  ; BTYPE (bv.of_Z (-20)) X0 T6 RISCV_BNE   (* bnez	T6, .LBB3_9 *)
  ; STORE (bv.of_Z 4) A1 A0 WORD   (* sw	A1, 4(A0) *)
  ; LOAD (bv.of_Z 0) A7 A1 false WORD   (* lw	A1, 0(A7) *)
  ; LOAD (bv.of_Z 0) T3 T3 false WORD   (* lw	T3, 0(T3) *)
  ; RTYPE T5 T4 A7 RISCV_OR   (* or	A7, T4, T5 *)
  ; RTYPE T1 A1 A1 RISCV_SLL   (* sll	A1, A1, T1 *)
  ; RTYPE T0 T3 T3 RISCV_SRL   (* srl	T3, T3, T0 *)
  ; RTYPE A5 A2 T4 RISCV_ADD   (* add	T4, A2, A5 *)
  ; LOAD (bv.of_Z 0) T4 T4 false WORD   (* lw	T4, 0(T4) *)
  ; RTYPE T2 A2 T2 RISCV_ADD   (* add	T2, A2, T2 *)
  ; LOAD (bv.of_Z 0) T2 T5 false WORD   (* lw	T5, 0(T2) *)
  ; RTYPE A3 A1 A1 RISCV_AND   (* and	A1, A1, A3 *)
  ; RTYPE T3 A1 T2 RISCV_OR   (* or	T2, A1, T3 *)
  ; RTYPE T1 T4 A1 RISCV_SLL   (* sll	A1, T4, T1 *)
  ; RTYPE T0 T5 T0 RISCV_SRL   (* srl	T0, T5, T0 *)
  ; RTYPE A3 A1 A1 RISCV_AND   (* and	A1, A1, A3 *)
  ; RTYPE T0 A1 T0 RISCV_OR   (* or	T0, A1, T0 *)
  ; RISCV_JAL (bv.of_Z 68) X0   (* j	.LBB3_15 *)
  ; RTYPE T5 T1 T1 RISCV_ADD   (* add	T1, T1, T5 *)
  ; RTYPE T5 T1 T0 RISCV_AND   (* and	T0, T1, T5 *)
  ; BTYPE (bv.of_Z 36) X0 T0 RISCV_BEQ   (* beqz	T0, .LBB3_14 *)
  ; SHIFTIOP (bv.of_Z 2) T0 T1 RISCV_SLLI   (* slli	T1, T0, 2 *)
  ; ITYPE (bv.of_Z 4) A0 T0 RISCV_ADDI   (* addi	T0, A0, 4 *)
  ; RTYPE T1 T0 T1 RISCV_ADD   (* add	T1, T0, T1 *)
  ; LOAD (bv.of_Z (-4)) T1 T2 false WORD   (* lw	T2, -4(T1) *)
  ; ITYPE (bv.of_Z (-4)) T1 T3 RISCV_ADDI   (* addi	T3, T1, -4 *)
  ; STORE (bv.of_Z 0) T2 T1 WORD   (* sw	T2, 0(T1) *)
  ; ITYPE (bv.of_Z 0) T3 T1 RISCV_ADDI   (* mv	T1, T3 *)
  ; BTYPE (bv.of_Z (-16)) T0 T3 RISCV_BNE   (* bne	T3, T0, .LBB3_13 *)
  ; STORE (bv.of_Z 4) A1 A0 WORD   (* sw	A1, 4(A0) *)
  ; LOAD (bv.of_Z 0) A7 T2 false WORD   (* lw	T2, 0(A7) *)
  ; RTYPE A5 A2 A1 RISCV_ADD   (* add	A1, A2, A5 *)
  ; LOAD (bv.of_Z 0) A1 T0 false WORD   (* lw	T0, 0(A1) *)
  ; ITYPE (bv.of_Z 0) A4 A7 RISCV_ADDI   (* mv	A7, A4 *)
  ; ITYPE (bv.of_Z 0) X0 T1 RISCV_ADDI   (* li	T1, 0 *)
  ; ITYPE (bv.of_Z 4) A0 A1 RISCV_ADDI   (* addi	A1, A0, 4 *)
  ; SHIFTIOP (bv.of_Z 1) A7 T4 RISCV_SRLI   (* srli	T4, A7, 1 *)
  ; SHIFTIOP (bv.of_Z 31) A7 T3 RISCV_SLLI   (* slli	T3, A7, 31 *)
  ; RTYPE T2 T3 T3 RISCV_OR   (* or	T3, T3, T2 *)
  ; RTYPE T0 T4 T2 RISCV_XOR   (* xor	T2, T4, T0 *)
  ; ITYPE (bv.of_Z 1) T2 T2 RISCV_SLTIU   (* seqz	T2, T2 *)
  ; ITYPE (bv.of_Z (-1)) T2 T2 RISCV_ADDI   (* addi	T2, T2, -1 *)
  ; RTYPE T4 T2 T2 RISCV_AND   (* and	T2, T2, T4 *)
  ; ITYPE (bv.of_Z 5) X0 T4 RISCV_ADDI   (* li	T4, 5 *)
  ; ITYPE (bv.of_Z 1) X0 T5 RISCV_ADDI   (* li	T5, 1 *)
  ; ITYPE (bv.of_Z 1) X0 T6 RISCV_ADDI   (* li	T6, 1 *)
  ; ITYPE (bv.of_Z (-1)) T4 T4 RISCV_ADDI   (* addi	T4, T4, -1 *)
  ; RTYPE T6 T2 S0 RISCV_SLL   (* sll	S0, T2, T6 *)
  ; RTYPE T4 T3 S1 RISCV_SRL   (* srl	S1, T3, T4 *)
  ; RTYPE S1 S0 S0 RISCV_OR   (* or	S0, S0, S1 *)
  ; RTYPE T0 S0 S1 RISCV_SUB   (* sub	S1, S0, T0 *)
  ; RTYPE T0 S0 S0 RISCV_XOR   (* xor	S0, S0, T0 *)
  ; RTYPE T0 S1 S2 RISCV_XOR   (* xor	S2, S1, T0 *)
  ; RTYPE S0 S2 S0 RISCV_AND   (* and	S0, S2, S0 *)
  ; RTYPE S1 S0 S0 RISCV_XOR   (* xor	S0, S0, S1 *)
  ; ITYPE (bv.of_Z (-1)) S0 S0 RISCV_XORI   (* not	S0, S0 *)
  ; SHIFTIOP (bv.of_Z 31) S0 S0 RISCV_SRLI   (* srli	S0, S0, 31 *)
  ; RTYPE T4 T2 S2 RISCV_SRL   (* srl	S2, T2, T4 *)
  ; RTYPE S0 S2 S0 RISCV_OR   (* or	S0, S2, S0 *)
  ; RTYPE T6 S1 S1 RISCV_SRL   (* srl	S1, S1, T6 *)
  ; RTYPE T4 T0 S2 RISCV_SLL   (* sll	S2, T0, T4 *)
  ; RTYPE S2 T3 S2 RISCV_SUB   (* sub	S2, T3, S2 *)
  ; RTYPE S0 X0 S3 RISCV_SUB   (* neg	S3, S0 *)
  ; RTYPE T2 S1 S1 RISCV_XOR   (* xor	S1, S1, T2 *)
  ; RTYPE S3 S1 S1 RISCV_AND   (* and	S1, S1, S3 *)
  ; RTYPE T2 S1 T2 RISCV_XOR   (* xor	T2, S1, T2 *)
  ; RTYPE T3 S2 S1 RISCV_XOR   (* xor	S1, S2, T3 *)
  ; RTYPE S3 S1 S1 RISCV_AND   (* and	S1, S1, S3 *)
  ; RTYPE T3 S1 T3 RISCV_XOR   (* xor	T3, S1, T3 *)
  ; RTYPE T4 S0 S0 RISCV_SLL   (* sll	S0, S0, T4 *)
  ; RTYPE T1 S0 T1 RISCV_OR   (* or	T1, S0, T1 *)
  ; ITYPE (bv.of_Z 1) T6 T6 RISCV_ADDI   (* addi	T6, T6, 1 *)
  ; BTYPE (bv.of_Z (-104)) T4 T5 RISCV_BLTU   (* bltu	T5, T4, .LBB3_16 *)
  ; ITYPE (bv.of_Z 32) X0 T4 RISCV_ADDI   (* li	T4, 32 *)
  ; BTYPE (bv.of_Z 16) T4 A6 RISCV_BGEU   (* bgeu	A6, T4, .LBB3_19 *)
  ; ITYPE (bv.of_Z 0) X0 A6 RISCV_ADDI   (* li	A6, 0 *)
  ; ITYPE (bv.of_Z 1) X0 A5 RISCV_ADDI   (* li	A5, 1 *)
  ; RISCV_JAL (bv.of_Z 212) X0   (* j	.LBB3_21 *)
  ; ITYPE (bv.of_Z 0) X0 A6 RISCV_ADDI   (* li	A6, 0 *)
  ; RTYPE T0 T3 T4 RISCV_SUB   (* sub	T4, T3, T0 *)
  ; RTYPE T0 T3 T3 RISCV_XOR   (* xor	T3, T3, T0 *)
  ; RTYPE T0 T4 T5 RISCV_XOR   (* xor	T5, T4, T0 *)
  ; RTYPE T3 T5 T3 RISCV_AND   (* and	T3, T5, T3 *)
  ; RTYPE T4 T3 T3 RISCV_XOR   (* xor	T3, T3, T4 *)
  ; ITYPE (bv.of_Z (-1)) T3 T3 RISCV_XORI   (* not	T3, T3 *)
  ; SHIFTIOP (bv.of_Z 31) T3 T3 RISCV_SRLI   (* srli	T3, T3, 31 *)
  ; RTYPE T1 T2 T1 RISCV_OR   (* or	T1, T2, T1 *)
  ; RTYPE T3 T1 T1 RISCV_OR   (* or	T1, T1, T3 *)
  ; RTYPE T0 A7 A7 RISCV_XOR   (* xor	A7, A7, T0 *)
  ; ITYPE (bv.of_Z 1) A7 T0 RISCV_SLTIU   (* seqz	T0, A7 *)
  ; ITYPE (bv.of_Z 1) T1 T2 RISCV_SLTIU   (* seqz	T2, T1 *)
  ; ITYPE (bv.of_Z 4) A2 A7 RISCV_ADDI   (* addi	A7, A2, 4 *)
  ; ITYPE (bv.of_Z (-1)) T2 T2 RISCV_ADDI   (* addi	T2, T2, -1 *)
  ; ITYPE (bv.of_Z (-1)) T1 T1 RISCV_ADDI   (* addi	T1, T1, -1 *)
  ; RTYPE T1 T2 T1 RISCV_AND   (* and	T1, T2, T1 *)
  ; RTYPE A3 T1 T2 RISCV_XOR   (* xor	T2, T1, A3 *)
  ; RTYPE T0 X0 T0 RISCV_SUB   (* neg	T0, T0 *)
  ; RTYPE T0 T2 T0 RISCV_AND   (* and	T0, T2, T0 *)
  ; RTYPE T1 T0 T0 RISCV_XOR   (* xor	T0, T0, T1 *)
  ; RTYPE A5 A1 T1 RISCV_ADD   (* add	T1, A1, A5 *)
  ; ITYPE (bv.of_Z 1) X0 A5 RISCV_ADDI   (* li	A5, 1 *)
  ; LOAD (bv.of_Z 0) A7 T2 false WORD   (* lw	T2, 0(A7) *)
  ; MULHU T3 T2 T0   (* mulhu	T3, T2, T0 -- fixed from asm_to_ast.py's raw Base.MUL form to Spec.v's Assembly.MULHU (rd rs1 rs2) smart constructor *)
  ; MUL T4 T2 T0   (* mul	T4, T2, T0 -- fixed from asm_to_ast.py's raw Base.MUL form to Spec.v's Assembly.MUL (rd rs1 rs2) smart constructor *)
  ; RTYPE A6 T4 A6 RISCV_ADD   (* add	A6, T4, A6 *)
  ; RTYPE T4 A6 T4 RISCV_SLTU   (* sltu	T4, A6, T4 *)
  ; RTYPE T4 T3 T3 RISCV_ADD   (* add	T3, T3, T4 *)
  ; SHIFTIOP (bv.of_Z 1) T3 T3 RISCV_SLLI   (* slli	T3, T3, 1 *)
  ; LOAD (bv.of_Z 0) A1 T4 false WORD   (* lw	T4, 0(A1) *)
  ; SHIFTIOP (bv.of_Z 31) A6 T5 RISCV_SRLI   (* srli	T5, A6, 31 *)
  ; RTYPE T3 T5 T3 RISCV_OR   (* or	T3, T5, T3 *)
  ; RTYPE A3 A6 A6 RISCV_AND   (* and	A6, A6, A3 *)
  ; RTYPE A6 T4 T4 RISCV_SUB   (* sub	T4, T4, A6 *)
  ; SHIFTIOP (bv.of_Z 31) T4 A6 RISCV_SRLI   (* srli	A6, T4, 31 *)
  ; RTYPE T3 A6 A6 RISCV_ADD   (* add	A6, A6, T3 *)
  ; RTYPE A3 T4 T3 RISCV_AND   (* and	T3, T4, A3 *)
  ; STORE (bv.of_Z 0) T3 A1 WORD   (* sw	T3, 0(A1) *)
  ; RTYPE T3 T2 T4 RISCV_XOR   (* xor	T4, T2, T3 *)
  ; ITYPE (bv.of_Z 1) T4 T4 RISCV_SLTIU   (* seqz	T4, T4 *)
  ; RTYPE T3 T2 T3 RISCV_SUB   (* sub	T3, T2, T3 *)
  ; ITYPE (bv.of_Z (-1)) T2 T2 RISCV_XORI   (* not	T2, T2 *)
  ; RTYPE T2 T3 T2 RISCV_AND   (* and	T2, T3, T2 *)
  ; SHIFTIOP (bv.of_Z 31) T2 T2 RISCV_SRLI   (* srli	T2, T2, 31 *)
  ; RTYPE T4 X0 T3 RISCV_SUB   (* neg	T3, T4 *)
  ; RTYPE A5 T2 A5 RISCV_XOR   (* xor	A5, T2, A5 *)
  ; RTYPE T3 A5 A5 RISCV_AND   (* and	A5, A5, T3 *)
  ; RTYPE T2 A5 A5 RISCV_XOR   (* xor	A5, A5, T2 *)
  ; ITYPE (bv.of_Z 4) A1 A1 RISCV_ADDI   (* addi	A1, A1, 4 *)
  ; ITYPE (bv.of_Z 4) A7 A7 RISCV_ADDI   (* addi	A7, A7, 4 *)
  ; BTYPE (bv.of_Z (-112)) T1 A1 RISCV_BNE   (* bne	A1, T1, .LBB3_20 *)
  ; RTYPE A6 A4 A7 RISCV_SUB   (* sub	A7, A4, A6 *)
  ; RTYPE A4 A6 A1 RISCV_XOR   (* xor	A1, A6, A4 *)
  ; RTYPE A6 A7 T0 RISCV_XOR   (* xor	T0, A7, A6 *)
  ; LOAD (bv.of_Z 0) A0 T1 false WORD   (* lw	T1, 0(A0) *)
  ; RTYPE A1 T0 T0 RISCV_AND   (* and	T0, T0, A1 *)
  ; RTYPE A7 T0 A7 RISCV_XOR   (* xor	A7, T0, A7 *)
  ; SHIFTIOP (bv.of_Z 31) A7 T0 RISCV_SRLI   (* srli	T0, A7, 31 *)
  ; ITYPE (bv.of_Z 63) T1 T1 RISCV_ADDI   (* addi	T1, T1, 63 *)
  ; SHIFTIOP (bv.of_Z 5) T1 A7 RISCV_SRLI   (* srli	A7, T1, 5 *)
  ; ITYPE (bv.of_Z 64) X0 T2 RISCV_ADDI   (* li	T2, 64 *)
  ; SHIFTIOP (bv.of_Z 2) A7 A7 RISCV_SLLI   (* slli	A7, A7, 2 *)
  ; BTYPE (bv.of_Z 80) T2 T1 RISCV_BLTU   (* bltu	T1, T2, .LBB3_24 *)
  ; ITYPE (bv.of_Z 0) X0 T3 RISCV_ADDI   (* li	T3, 0 *)
  ; ITYPE (bv.of_Z 0) T0 T4 RISCV_ADDI   (* mv	T4, T0 *)
  ; RTYPE T4 X0 T4 RISCV_SUB   (* neg	T4, T4 *)
  ; ITYPE (bv.of_Z 4) A2 T5 RISCV_ADDI   (* addi	T5, A2, 4 *)
  ; ITYPE (bv.of_Z 4) A0 T6 RISCV_ADDI   (* addi	T6, A0, 4 *)
  ; RTYPE A7 A2 S0 RISCV_ADD   (* add	S0, A2, A7 *)
  ; LOAD (bv.of_Z 0) T6 S1 false WORD   (* lw	S1, 0(T6) *)
  ; LOAD (bv.of_Z 0) T5 S2 false WORD   (* lw	S2, 0(T5) *)
  ; RTYPE T3 S1 T3 RISCV_ADD   (* add	T3, S1, T3 *)
  ; RTYPE S2 T3 S2 RISCV_ADD   (* add	S2, T3, S2 *)
  ; SHIFTIOP (bv.of_Z 31) S2 T3 RISCV_SRLI   (* srli	T3, S2, 31 *)
  ; RTYPE A3 S2 S2 RISCV_AND   (* and	S2, S2, A3 *)
  ; RTYPE S1 S2 S2 RISCV_XOR   (* xor	S2, S2, S1 *)
  ; RTYPE T4 S2 S2 RISCV_AND   (* and	S2, S2, T4 *)
  ; RTYPE S1 S2 S1 RISCV_XOR   (* xor	S1, S2, S1 *)
  ; STORE (bv.of_Z 0) S1 T6 WORD   (* sw	S1, 0(T6) *)
  ; ITYPE (bv.of_Z 4) T5 T5 RISCV_ADDI   (* addi	T5, T5, 4 *)
  ; ITYPE (bv.of_Z 4) T6 T6 RISCV_ADDI   (* addi	T6, T6, 4 *)
  ; BTYPE (bv.of_Z (-48)) S0 T5 RISCV_BNE   (* bne	T5, S0, .LBB3_23 *)
  ; BTYPE (bv.of_Z 108) T2 T1 RISCV_BLTU   (* bltu	T1, T2, .LBB3_27 *)
  ; ITYPE (bv.of_Z 0) X0 T1 RISCV_ADDI   (* li	T1, 0 *)
  ; RTYPE A4 A6 A6 RISCV_SUB   (* sub	A6, A6, A4 *)
  ; RTYPE A4 A6 A4 RISCV_XOR   (* xor	A4, A6, A4 *)
  ; RTYPE A1 A4 A1 RISCV_AND   (* and	A1, A4, A1 *)
  ; RTYPE A6 A1 A1 RISCV_XOR   (* xor	A1, A1, A6 *)
  ; SHIFTIOP (bv.of_Z 31) A1 A1 RISCV_SRLI   (* srli	A1, A1, 31 *)
  ; ITYPE (bv.of_Z (-1)) T0 A4 RISCV_XORI   (* not	A4, T0 *)
  ; RTYPE A5 A1 A1 RISCV_OR   (* or	A1, A1, A5 *)
  ; RTYPE A4 A1 A1 RISCV_AND   (* and	A1, A1, A4 *)
  ; RTYPE A1 X0 A1 RISCV_SUB   (* neg	A1, A1 *)
  ; ITYPE (bv.of_Z 4) A2 A4 RISCV_ADDI   (* addi	A4, A2, 4 *)
  ; ITYPE (bv.of_Z 4) A0 A0 RISCV_ADDI   (* addi	A0, A0, 4 *)
  ; RTYPE A7 A2 A2 RISCV_ADD   (* add	A2, A2, A7 *)
  ; LOAD (bv.of_Z 0) A0 A5 false WORD   (* lw	A5, 0(A0) *)
  ; LOAD (bv.of_Z 0) A4 A6 false WORD   (* lw	A6, 0(A4) *)
  ; RTYPE T1 A5 T1 RISCV_ADD   (* add	T1, A5, T1 *)
  ; RTYPE A6 T1 A6 RISCV_SUB   (* sub	A6, T1, A6 *)
  ; SHIFTIOP (bv.of_Z 31) A6 T1 RISCV_SRAI   (* srai	T1, A6, 31 *)
  ; RTYPE A3 A6 A6 RISCV_AND   (* and	A6, A6, A3 *)
  ; RTYPE A5 A6 A6 RISCV_XOR   (* xor	A6, A6, A5 *)
  ; RTYPE A1 A6 A6 RISCV_AND   (* and	A6, A6, A1 *)
  ; RTYPE A5 A6 A5 RISCV_XOR   (* xor	A5, A6, A5 *)
  ; STORE (bv.of_Z 0) A5 A0 WORD   (* sw	A5, 0(A0) *)
  ; ITYPE (bv.of_Z 4) A4 A4 RISCV_ADDI   (* addi	A4, A4, 4 *)
  ; ITYPE (bv.of_Z 4) A0 A0 RISCV_ADDI   (* addi	A0, A0, 4 *)
  ; BTYPE (bv.of_Z (-48)) A2 A4 RISCV_BNE   (* bne	A4, A2, .LBB3_26 *)
  ; LOAD (bv.of_Z 12) X2 S0 false WORD   (* lw	S0, 12(X2)                      # 4-byte Folded Reload *)
  ; LOAD (bv.of_Z 8) X2 S1 false WORD   (* lw	S1, 8(X2)                       # 4-byte Folded Reload *)
  ; LOAD (bv.of_Z 4) X2 S2 false WORD   (* lw	S2, 4(X2)                       # 4-byte Folded Reload *)
  ; LOAD (bv.of_Z 0) X2 S3 false WORD   (* lw	S3, 0(X2)                       # 4-byte Folded Reload *)
  ; ITYPE (bv.of_Z 16) X2 X2 RISCV_ADDI   (* addi	X2, X2, 16 *)
  ].

Definition zzmuladdfulln4_reg_specs_rel : list reg_spec_rel :=
  [ (A0, true,  PVBaseOff 1128)
  ; (A1, false, PVExist)
  ; (A2, true,  PVBaseOff 1148)
  ; (X2, true,  PVBaseOff 1184)
  ; (A3, false, PVExist); (A4, false, PVExist); (A5, false, PVExist)
  ; (A6, false, PVExist); (A7, false, PVExist)
  ; (T0, false, PVExist); (T1, false, PVExist); (T2, false, PVExist)
  ; (T3, false, PVExist); (T4, false, PVExist); (T5, false, PVExist)
  ; (T6, false, PVExist)
  ; (S0, false, PVExist); (S1, false, PVExist); (S2, false, PVExist)
  ; (S3, false, PVExist)
  ].

Definition zzmuladdfulln4_x_specs_rel : list mem_spec_rel :=
  [ (1128%N, true,  PVConst (bv.of_N 127))
  ; (1132%N, false, PVExist); (1136%N, false, PVExist)
  ; (1140%N, false, PVExist); (1144%N, false, PVExist)
  ].

Definition zzmuladdfulln4_m_specs_rel : list mem_spec_rel :=
  [ (1148%N, true, PVConst (bv.of_N 127))
  ; (1152%N, true, PVExist); (1156%N, true, PVExist)
  ; (1160%N, true, PVExist); (1164%N, true, PVExist)
  ].

Definition zzmuladdfulln4_stack_specs_rel : list mem_spec_rel :=
  [ (1168%N, false, PVExist); (1172%N, false, PVExist)
  ; (1176%N, false, PVExist); (1180%N, false, PVExist)
  ].

Definition zzmuladdfulln4_mem_specs_rel : list mem_spec_rel :=
  zzmuladdfulln4_x_specs_rel ++ zzmuladdfulln4_m_specs_rel
  ++ zzmuladdfulln4_stack_specs_rel.

Definition zzmuladdfulln4_cfg_contract_param (ia : N)
    : @CFGVerifierContract ["p" :: ty_xlenbits] :=
  gen_contract_rel ia zzmuladdfulln4_reg_specs_rel zzmuladdfulln4_mem_specs_rel
    zzmuladdfulln4_instrs [] 1184%N
    (pcOutOfInstrs_exitCond ia zzmuladdfulln4_instrs) 500.

Lemma valid_zzmuladdfulln4_cfg_contract_param (ia : N) :
  ValidCFGVerifierContract (zzmuladdfulln4_cfg_contract_param ia).
Proof. intros; vm_compute; solve_vc; solve_symbase_fetch. Qed.
