(* ========================================================================= *)
(* Example/ZZMuladdFullN2.v -- THROWAWAY, PLAN-muladd-full.md Phase 2/3.      *)
(*                                                                           *)
(* Whole-function BearSSL `br_i31_muladd_small` (src/int/i31_muladd.c),      *)
(* current upstream HEAD as of 2026-08-11 -- verified IDENTICAL to the       *)
(* paper's pinned commit 79c060e for this file and for inner.h's MUX/EQ/GT   *)
(* (no hardening has ever landed upstream). Compiled WHOLE with              *)
(* `clang --target=riscv32 -march=rv32im -mabi=ilp32 -ffreestanding -O2`,    *)
(* with `br_divrem` (src/int/i32_div32.c), `br_i31_add` (i31_add.c) and      *)
(* `br_i31_sub` (i31_sub.c) all INLINED via -flto (confirmed: verbatim       *)
(* single-TU compile and a real -flto link of the four separate objects      *)
(* agree byte-for-byte), and a hand-supplied `memmove` replacement (no libc  *)
(* in this pipeline) inlined the same way.                                   *)
(*                                                                           *)
(* THREE deviations from the literal upstream source, each disclosed:        *)
(*                                                                           *)
(* 1. HARDENING (changes behaviour under adversarial compilers, not          *)
(*    semantics): the raw source is NOT constant-time under clang 18.1.3 at  *)
(*    -O2 -- confirmed by compiling it unmodified and reading the resulting  *)
(*    assembly. Two distinct secret-dependent branches were found:           *)
(*      (a) `q = MUX(EQ(a0,b0), 0x7FFFFFFF, MUX(EQ(g,0),0,g-1))` -- the SAME *)
(*          finding already documented for the landed `muladd_q` snippet     *)
(*          (BearSSLMuladd.v), reproduced here in the whole-function build.  *)
(*      (b) NEW, found only once `br_i31_add`/`br_i31_sub` are INLINED: the  *)
(*          per-word `MUX(ctl, naw & 0x7FFFFFFF, aw)` compiles branch-free   *)
(*          when br_i31_add is compiled standalone, but reforms into a real  *)
(*          per-iteration branch once inlined into this caller -- the same   *)
(*          InstCombine behaviour, a different trigger, confirmed by         *)
(*          compiling br_i31_add.c alone (clean) vs. inlined (branchy).      *)
(*    Fixed with the SAME technique `muladd_q` already uses -- an empty      *)
(*    inline-asm optimisation barrier, `opaque(v) { __asm__("":"+r"(v));     *)
(*    return v; }` -- applied at every site whose value reaches a MUX or a   *)
(*    cross-function ctl argument: `MUX(opaque(EQ(a0,b0)), ...)`,            *)
(*    `MUX(opaque(EQ(nxw,mw)), ...)`, `br_i31_add(x,m,opaque(over))`,        *)
(*    `br_i31_sub(x,m,opaque(under))`, and `ctl = opaque(ctl);` added once   *)
(*    at the top of br_i31_add/br_i31_sub themselves (belt-and-suspenders,   *)
(*    since that is exactly where (b) was found). Re-verified branch-free    *)
(*    and call-free after hardening, both single-TU and via a real -flto     *)
(*    link of the four separate hardened objects.                            *)
(*                                                                           *)
(* 2. MEMMOVE REPLACEMENT: this pipeline has no libc, so the one call to     *)
(*    `memmove(x+2, x+1, (mlen-1)*sizeof *x)` needs a local stand-in.        *)
(*    Written as a WORD-copy loop (not the generic byte-copy a real memmove  *)
(*    must support), which is sound here specifically because the sole call *)
(*    site always passes 4-byte-aligned `uint32_t*` pointers and a size      *)
(*    that is an exact multiple of 4 -- the same guarantee a real optimised  *)
(*    memmove's aligned fast path checks before dispatching to a word loop   *)
(*    instead of a byte loop. This keeps the whole function word-granular    *)
(*    (plain `gen_contract_rel`), avoiding the `_rel_bytes` machinery        *)
(*    `check_scalar` needed for its genuinely byte-addressed `lbu` accesses. *)
(*                                                                           *)
(* 3. DIVISION LOOP TRIP COUNT: `br_divrem`'s `for (k = 31; k > 0; k--)` is  *)
(*    fixed by the division algorithm, not by `mlen` -- it runs in full      *)
(*    regardless of limb count, so it cannot be shrunk by choosing a small   *)
(*    `mlen` the way check_scalar_full's own small-N probes shrunk a real    *)
(*    loop bound. Since CORRECTNESS of the quotient is irrelevant to a       *)
(*    NONINTERFERENCE proof -- only the shape (branch-freedom, public loop   *)
(*    bound) matters -- the loop count is patched to match this probe's      *)
(*    `mlen` AFTER compilation: the two `li <reg>, 32` trip-count-setting    *)
(*    immediates (one per inlined copy: the dead small-modulus path and the  *)
(*    live main path) are changed to `li <reg>, 3` (2 real iterations),      *)
(*    a PURE NUMERAL EDIT to already-compiled text that cannot touch the     *)
(*    branch structure the optimiser already committed to -- verified by     *)
(*    re-scanning the patched region for stray branches (none). Kept as a    *)
(*    genuine backward-branch loop (not made a compile-time-unrollable       *)
(*    constant) specifically to preserve loop control-flow shape, per        *)
(*    cfgver-new-example's full-unrolling warning.                           *)
(*                                                                           *)
(* Memory layout (code, x[], m[], stack -- the usual contiguous convention): *)
(*   code   : p+0    .. p+1127  (282 instrs * 4 bytes = 1128 bytes)          *)
(*   x[]    : p+1128 .. p+1139  (3 words: x[0]=bitlen PINNED 63 (PUBLIC --   *)
(*            br_i31_add/sub read a[0] for THEIR OWN loop bound, so it must  *)
(*            match m[0]); x[1],x[2] SECRET, the value being reduced)        *)
(*   m[]    : p+1140 .. p+1151  (3 words: m[0]=bitlen PINNED 63 (PUBLIC,     *)
(*            BearSSL's own comment: "we accept to leak that length");       *)
(*            m[1],m[2] PUBLIC-but-unpinned, the modulus limbs)              *)
(*   stack  : p+1152 .. p+1167  (4 words: S0-S3 spill slots, SECRET-valued   *)
(*            but immaterial -- pure save/restore, never branched on)        *)
(*   A0=&x[0]=p+1128, A2=&m[0]=p+1140, X2(sp)=p+1168 (so `addi sp,sp,-16`    *)
(*   lands exactly on the stack region above). Bound 1168.                   *)
(*                                                                           *)
(* m[0]=x[0]=63 gives mlen=(63+31)>>5=2 for muladd's own accumulate loop,    *)
(* AND (63+63)>>5=3 (so add/sub's own `u<3` loop runs u=1,2 -- also 2 trips) *)
(* -- the two loop-bound formulas differ but agree at this pinned value.     *)
(* mblr=63&31=31<>0 so the shift-extraction ELSE branch (with its own        *)
(* memmove call) is what actually runs, exercising the harder of the two.    *)
(*                                                                           *)
(* The two early-return branches (`m_bitlen==0`, `m_bitlen<=31`) are         *)
(* provably infeasible against the PINNED CONCRETE bitlen 63 by direct       *)
(* literal comparison, so their bodies (including the small-modulus path's   *)
(* OWN inlined division-loop copy and the shared early-exit `ret`) are       *)
(* never symbolically visited -- same mechanism, same `extra_exit_offs = []` *)
(* choice, as ZZCheckScalarFullN2.v's own dead `if (klen > 32) return 0;`    *)
(* block.                                                                    *)
(*                                                                           *)
(* Translated with tools/asm_to_ast.py --drop-ret (after the loop-count      *)
(* patch above); register names substituted from the tool's local a0..      *)
(* aliases to this project's existing X0-X2/A0-A7/T0-T6; S0-S3 are NOT       *)
(* pre-existing project aliases (this is the first example to need them)    *)
(* so they are defined locally below.                                       *)
(* ------------------------------------------------------------------------ *)

From Katamaran Require Export RiscvPmp.CFGVer.Example.Prelude.

Definition S0 : RegIdx := bv.of_nat 8.
Definition S1 : RegIdx := bv.of_nat 9.
Definition S2 : RegIdx := bv.of_nat 18.
Definition S3 : RegIdx := bv.of_nat 19.

Definition zzmuladdfulln2_instrs : list AST :=
  [ LOAD (bv.of_Z 0) A2 T0 false WORD   (* lw	T0, 0(A2) *)
  ; BTYPE (bv.of_Z 212) X0 T0 RISCV_BEQ   (* beqz	T0, .LBB3_5 *)
  ; ITYPE (bv.of_Z 31) X0 A3 RISCV_ADDI   (* li	A3, 31 *)
  ; BTYPE (bv.of_Z 208) T0 A3 RISCV_BLTU   (* bltu	A3, T0, .LBB3_6 *)
  ; LOAD (bv.of_Z 4) A0 A3 false WORD   (* lw	A3, 4(A0) *)
  ; LOAD (bv.of_Z 4) A2 A2 false WORD   (* lw	A2, 4(A2) *)
  ; SHIFTIOP (bv.of_Z 1) A3 A4 RISCV_SRLI   (* srli	A4, A3, 1 *)
  ; SHIFTIOP (bv.of_Z 31) A3 A3 RISCV_SLLI   (* slli	A3, A3, 31 *)
  ; RTYPE A1 A3 A1 RISCV_OR   (* or	A1, A3, A1 *)
  ; RTYPE A2 A4 A3 RISCV_XOR   (* xor	A3, A4, A2 *)
  ; ITYPE (bv.of_Z 1) A3 A3 RISCV_SLTIU   (* seqz	A3, A3 *)
  ; ITYPE (bv.of_Z (-1)) A3 A3 RISCV_ADDI   (* addi	A3, A3, -1 *)
  ; RTYPE A4 A3 A3 RISCV_AND   (* and	A3, A3, A4 *)
  ; ITYPE (bv.of_Z 3) X0 A4 RISCV_ADDI   (* li	A4, 3 *)
  ; ITYPE (bv.of_Z 1) X0 A5 RISCV_ADDI   (* li	A5, 1 *)
  ; ITYPE (bv.of_Z 1) X0 A6 RISCV_ADDI   (* li	A6, 1 *)
  ; ITYPE (bv.of_Z (-1)) A4 A4 RISCV_ADDI   (* addi	A4, A4, -1 *)
  ; RTYPE A6 A3 A7 RISCV_SLL   (* sll	A7, A3, A6 *)
  ; RTYPE A4 A1 T0 RISCV_SRL   (* srl	T0, A1, A4 *)
  ; RTYPE T0 A7 A7 RISCV_OR   (* or	A7, A7, T0 *)
  ; RTYPE A2 A7 T0 RISCV_SUB   (* sub	T0, A7, A2 *)
  ; RTYPE A2 A7 A7 RISCV_XOR   (* xor	A7, A7, A2 *)
  ; RTYPE A2 T0 T1 RISCV_XOR   (* xor	T1, T0, A2 *)
  ; RTYPE A7 T1 A7 RISCV_AND   (* and	A7, T1, A7 *)
  ; RTYPE T0 A7 A7 RISCV_XOR   (* xor	A7, A7, T0 *)
  ; ITYPE (bv.of_Z (-1)) A7 A7 RISCV_XORI   (* not	A7, A7 *)
  ; SHIFTIOP (bv.of_Z 31) A7 A7 RISCV_SRLI   (* srli	A7, A7, 31 *)
  ; RTYPE A4 A3 T1 RISCV_SRL   (* srl	T1, A3, A4 *)
  ; RTYPE A7 T1 A7 RISCV_OR   (* or	A7, T1, A7 *)
  ; RTYPE A6 T0 T0 RISCV_SRL   (* srl	T0, T0, A6 *)
  ; RTYPE A4 A2 T1 RISCV_SLL   (* sll	T1, A2, A4 *)
  ; RTYPE T1 A1 T1 RISCV_SUB   (* sub	T1, A1, T1 *)
  ; RTYPE A7 X0 A7 RISCV_SUB   (* neg	A7, A7 *)
  ; RTYPE A3 T0 T0 RISCV_XOR   (* xor	T0, T0, A3 *)
  ; RTYPE A7 T0 T0 RISCV_AND   (* and	T0, T0, A7 *)
  ; RTYPE A3 T0 A3 RISCV_XOR   (* xor	A3, T0, A3 *)
  ; RTYPE A1 T1 T0 RISCV_XOR   (* xor	T0, T1, A1 *)
  ; RTYPE A7 T0 A7 RISCV_AND   (* and	A7, T0, A7 *)
  ; RTYPE A1 A7 A1 RISCV_XOR   (* xor	A1, A7, A1 *)
  ; ITYPE (bv.of_Z 1) A6 A6 RISCV_ADDI   (* addi	A6, A6, 1 *)
  ; BTYPE (bv.of_Z (-96)) A4 A5 RISCV_BLTU   (* bltu	A5, A4, .LBB3_3 *)
  ; RTYPE A2 A1 A4 RISCV_SUB   (* sub	A4, A1, A2 *)
  ; RTYPE A2 A1 A5 RISCV_XOR   (* xor	A5, A1, A2 *)
  ; RTYPE A2 A4 A2 RISCV_XOR   (* xor	A2, A4, A2 *)
  ; RTYPE A5 A2 A2 RISCV_AND   (* and	A2, A2, A5 *)
  ; RTYPE A4 A2 A2 RISCV_XOR   (* xor	A2, A2, A4 *)
  ; ITYPE (bv.of_Z (-1)) A2 A2 RISCV_XORI   (* not	A2, A2 *)
  ; SHIFTIOP (bv.of_Z 31) A2 A2 RISCV_SRLI   (* srli	A2, A2, 31 *)
  ; RTYPE A2 A3 A2 RISCV_OR   (* or	A2, A3, A2 *)
  ; RTYPE A2 X0 A2 RISCV_SUB   (* neg	A2, A2 *)
  ; RTYPE A1 A4 A4 RISCV_XOR   (* xor	A4, A4, A1 *)
  ; RTYPE A2 A4 A2 RISCV_AND   (* and	A2, A4, A2 *)
  ; RTYPE A1 A2 A1 RISCV_XOR   (* xor	A1, A2, A1 *)
  ; STORE (bv.of_Z 4) A1 A0 WORD   (* sw	A1, 4(A0) *)
  ; RISCV_JALR (bv.of_Z 0) X1 X0   (* ret *)
  ; ITYPE (bv.of_Z (-16)) X2 X2 RISCV_ADDI   (* addi	X2, X2, -16 *)
  ; STORE (bv.of_Z 12) S0 X2 WORD   (* sw	S0, 12(X2)                      # 4-byte Folded Spill *)
  ; STORE (bv.of_Z 8) S1 X2 WORD   (* sw	S1, 8(X2)                       # 4-byte Folded Spill *)
  ; STORE (bv.of_Z 4) S2 X2 WORD   (* sw	S2, 4(X2)                       # 4-byte Folded Spill *)
  ; STORE (bv.of_Z 0) S3 X2 WORD   (* sw	S3, 0(X2)                       # 4-byte Folded Spill *)
  ; UTYPE (bv.of_Z 524288) A3 RISCV_LUI   (* lui	A3, 524288 *)
  ; ITYPE (bv.of_Z (-1)) A3 A3 RISCV_ADDI   (* addi	A3, A3, -1 *)
  ; ITYPE (bv.of_Z 31) T0 A6 RISCV_ADDI   (* addi	A6, T0, 31 *)
  ; SHIFTIOP (bv.of_Z 5) A6 T1 RISCV_SRLI   (* srli	T1, A6, 5 *)
  ; SHIFTIOP (bv.of_Z 2) T1 A5 RISCV_SLLI   (* slli	A5, T1, 2 *)
  ; RTYPE A5 A0 A7 RISCV_ADD   (* add	A7, A0, A5 *)
  ; LOAD (bv.of_Z 0) A7 A4 false WORD   (* lw	A4, 0(A7) *)
  ; UTYPE (bv.of_Z 262144) T5 RISCV_LUI   (* lui	T5, 262144 *)
  ; ITYPE (bv.of_Z 31) T0 T0 RISCV_ANDI   (* andi	T0, T0, 31 *)
  ; ITYPE (bv.of_Z (-1)) T5 T5 RISCV_ADDI   (* addi	T5, T5, -1 *)
  ; BTYPE (bv.of_Z 148) X0 T0 RISCV_BEQ   (* beqz	T0, .LBB3_11 *)
  ; ITYPE (bv.of_Z (-1)) T1 T6 RISCV_ADDI   (* addi	T6, T1, -1 *)
  ; SHIFTIOP (bv.of_Z 2) T6 T2 RISCV_SLLI   (* slli	T2, T6, 2 *)
  ; RTYPE T2 A0 T3 RISCV_ADD   (* add	T3, A0, T2 *)
  ; LOAD (bv.of_Z 0) T3 T4 false WORD   (* lw	T4, 0(T3) *)
  ; ITYPE (bv.of_Z 31) T0 T1 RISCV_XORI   (* xori	T1, T0, 31 *)
  ; RTYPE T1 A4 S0 RISCV_SLL   (* sll	S0, A4, T1 *)
  ; RTYPE T0 T4 T4 RISCV_SRL   (* srl	T4, T4, T0 *)
  ; RTYPE T5 T6 T6 RISCV_AND   (* and	T6, T6, T5 *)
  ; RTYPE A3 S0 T5 RISCV_AND   (* and	T5, S0, A3 *)
  ; BTYPE (bv.of_Z 40) X0 T6 RISCV_BEQ   (* beqz	T6, .LBB3_10 *)
  ; SHIFTIOP (bv.of_Z 2) T6 S0 RISCV_SLLI   (* slli	S0, T6, 2 *)
  ; RTYPE A0 S0 S0 RISCV_ADD   (* add	S0, S0, A0 *)
  ; ITYPE (bv.of_Z 4) S0 S0 RISCV_ADDI   (* addi	S0, S0, 4 *)
  ; LOAD (bv.of_Z (-4)) S0 S1 false WORD   (* lw	S1, -4(S0) *)
  ; ITYPE (bv.of_Z (-1)) T6 T6 RISCV_ADDI   (* addi	T6, T6, -1 *)
  ; ITYPE (bv.of_Z (-4)) S0 S2 RISCV_ADDI   (* addi	S2, S0, -4 *)
  ; STORE (bv.of_Z 0) S1 S0 WORD   (* sw	S1, 0(S0) *)
  ; ITYPE (bv.of_Z 0) S2 S0 RISCV_ADDI   (* mv	S0, S2 *)
  ; BTYPE (bv.of_Z (-20)) X0 T6 RISCV_BNE   (* bnez	T6, .LBB3_9 *)
  ; STORE (bv.of_Z 4) A1 A0 WORD   (* sw	A1, 4(A0) *)
  ; LOAD (bv.of_Z 0) A7 A1 false WORD   (* lw	A1, 0(A7) *)
  ; LOAD (bv.of_Z 0) T3 T3 false WORD   (* lw	T3, 0(T3) *)
  ; RTYPE T5 T4 A7 RISCV_OR   (* or	A7, T4, T5 *)
  ; RTYPE T1 A1 A1 RISCV_SLL   (* sll	A1, A1, T1 *)
  ; RTYPE T0 T3 T3 RISCV_SRL   (* srl	T3, T3, T0 *)
  ; RTYPE A5 A2 T4 RISCV_ADD   (* add	T4, A2, A5 *)
  ; LOAD (bv.of_Z 0) T4 T4 false WORD   (* lw	T4, 0(T4) *)
  ; RTYPE T2 A2 T2 RISCV_ADD   (* add	T2, A2, T2 *)
  ; LOAD (bv.of_Z 0) T2 T5 false WORD   (* lw	T5, 0(T2) *)
  ; RTYPE A3 A1 A1 RISCV_AND   (* and	A1, A1, A3 *)
  ; RTYPE T3 A1 T2 RISCV_OR   (* or	T2, A1, T3 *)
  ; RTYPE T1 T4 A1 RISCV_SLL   (* sll	A1, T4, T1 *)
  ; RTYPE T0 T5 T0 RISCV_SRL   (* srl	T0, T5, T0 *)
  ; RTYPE A3 A1 A1 RISCV_AND   (* and	A1, A1, A3 *)
  ; RTYPE T0 A1 T0 RISCV_OR   (* or	T0, A1, T0 *)
  ; RISCV_JAL (bv.of_Z 68) X0   (* j	.LBB3_15 *)
  ; RTYPE T5 T1 T1 RISCV_ADD   (* add	T1, T1, T5 *)
  ; RTYPE T5 T1 T0 RISCV_AND   (* and	T0, T1, T5 *)
  ; BTYPE (bv.of_Z 36) X0 T0 RISCV_BEQ   (* beqz	T0, .LBB3_14 *)
  ; SHIFTIOP (bv.of_Z 2) T0 T1 RISCV_SLLI   (* slli	T1, T0, 2 *)
  ; ITYPE (bv.of_Z 4) A0 T0 RISCV_ADDI   (* addi	T0, A0, 4 *)
  ; RTYPE T1 T0 T1 RISCV_ADD   (* add	T1, T0, T1 *)
  ; LOAD (bv.of_Z (-4)) T1 T2 false WORD   (* lw	T2, -4(T1) *)
  ; ITYPE (bv.of_Z (-4)) T1 T3 RISCV_ADDI   (* addi	T3, T1, -4 *)
  ; STORE (bv.of_Z 0) T2 T1 WORD   (* sw	T2, 0(T1) *)
  ; ITYPE (bv.of_Z 0) T3 T1 RISCV_ADDI   (* mv	T1, T3 *)
  ; BTYPE (bv.of_Z (-16)) T0 T3 RISCV_BNE   (* bne	T3, T0, .LBB3_13 *)
  ; STORE (bv.of_Z 4) A1 A0 WORD   (* sw	A1, 4(A0) *)
  ; LOAD (bv.of_Z 0) A7 T2 false WORD   (* lw	T2, 0(A7) *)
  ; RTYPE A5 A2 A1 RISCV_ADD   (* add	A1, A2, A5 *)
  ; LOAD (bv.of_Z 0) A1 T0 false WORD   (* lw	T0, 0(A1) *)
  ; ITYPE (bv.of_Z 0) A4 A7 RISCV_ADDI   (* mv	A7, A4 *)
  ; ITYPE (bv.of_Z 0) X0 T1 RISCV_ADDI   (* li	T1, 0 *)
  ; ITYPE (bv.of_Z 4) A0 A1 RISCV_ADDI   (* addi	A1, A0, 4 *)
  ; SHIFTIOP (bv.of_Z 1) A7 T4 RISCV_SRLI   (* srli	T4, A7, 1 *)
  ; SHIFTIOP (bv.of_Z 31) A7 T3 RISCV_SLLI   (* slli	T3, A7, 31 *)
  ; RTYPE T2 T3 T3 RISCV_OR   (* or	T3, T3, T2 *)
  ; RTYPE T0 T4 T2 RISCV_XOR   (* xor	T2, T4, T0 *)
  ; ITYPE (bv.of_Z 1) T2 T2 RISCV_SLTIU   (* seqz	T2, T2 *)
  ; ITYPE (bv.of_Z (-1)) T2 T2 RISCV_ADDI   (* addi	T2, T2, -1 *)
  ; RTYPE T4 T2 T2 RISCV_AND   (* and	T2, T2, T4 *)
  ; ITYPE (bv.of_Z 3) X0 T4 RISCV_ADDI   (* li	T4, 3 *)
  ; ITYPE (bv.of_Z 1) X0 T5 RISCV_ADDI   (* li	T5, 1 *)
  ; ITYPE (bv.of_Z 1) X0 T6 RISCV_ADDI   (* li	T6, 1 *)
  ; ITYPE (bv.of_Z (-1)) T4 T4 RISCV_ADDI   (* addi	T4, T4, -1 *)
  ; RTYPE T6 T2 S0 RISCV_SLL   (* sll	S0, T2, T6 *)
  ; RTYPE T4 T3 S1 RISCV_SRL   (* srl	S1, T3, T4 *)
  ; RTYPE S1 S0 S0 RISCV_OR   (* or	S0, S0, S1 *)
  ; RTYPE T0 S0 S1 RISCV_SUB   (* sub	S1, S0, T0 *)
  ; RTYPE T0 S0 S0 RISCV_XOR   (* xor	S0, S0, T0 *)
  ; RTYPE T0 S1 S2 RISCV_XOR   (* xor	S2, S1, T0 *)
  ; RTYPE S0 S2 S0 RISCV_AND   (* and	S0, S2, S0 *)
  ; RTYPE S1 S0 S0 RISCV_XOR   (* xor	S0, S0, S1 *)
  ; ITYPE (bv.of_Z (-1)) S0 S0 RISCV_XORI   (* not	S0, S0 *)
  ; SHIFTIOP (bv.of_Z 31) S0 S0 RISCV_SRLI   (* srli	S0, S0, 31 *)
  ; RTYPE T4 T2 S2 RISCV_SRL   (* srl	S2, T2, T4 *)
  ; RTYPE S0 S2 S0 RISCV_OR   (* or	S0, S2, S0 *)
  ; RTYPE T6 S1 S1 RISCV_SRL   (* srl	S1, S1, T6 *)
  ; RTYPE T4 T0 S2 RISCV_SLL   (* sll	S2, T0, T4 *)
  ; RTYPE S2 T3 S2 RISCV_SUB   (* sub	S2, T3, S2 *)
  ; RTYPE S0 X0 S3 RISCV_SUB   (* neg	S3, S0 *)
  ; RTYPE T2 S1 S1 RISCV_XOR   (* xor	S1, S1, T2 *)
  ; RTYPE S3 S1 S1 RISCV_AND   (* and	S1, S1, S3 *)
  ; RTYPE T2 S1 T2 RISCV_XOR   (* xor	T2, S1, T2 *)
  ; RTYPE T3 S2 S1 RISCV_XOR   (* xor	S1, S2, T3 *)
  ; RTYPE S3 S1 S1 RISCV_AND   (* and	S1, S1, S3 *)
  ; RTYPE T3 S1 T3 RISCV_XOR   (* xor	T3, S1, T3 *)
  ; RTYPE T4 S0 S0 RISCV_SLL   (* sll	S0, S0, T4 *)
  ; RTYPE T1 S0 T1 RISCV_OR   (* or	T1, S0, T1 *)
  ; ITYPE (bv.of_Z 1) T6 T6 RISCV_ADDI   (* addi	T6, T6, 1 *)
  ; BTYPE (bv.of_Z (-104)) T4 T5 RISCV_BLTU   (* bltu	T5, T4, .LBB3_16 *)
  ; ITYPE (bv.of_Z 32) X0 T4 RISCV_ADDI   (* li	T4, 32 *)
  ; BTYPE (bv.of_Z 16) T4 A6 RISCV_BGEU   (* bgeu	A6, T4, .LBB3_19 *)
  ; ITYPE (bv.of_Z 0) X0 A6 RISCV_ADDI   (* li	A6, 0 *)
  ; ITYPE (bv.of_Z 1) X0 A5 RISCV_ADDI   (* li	A5, 1 *)
  ; RISCV_JAL (bv.of_Z 212) X0   (* j	.LBB3_21 *)
  ; ITYPE (bv.of_Z 0) X0 A6 RISCV_ADDI   (* li	A6, 0 *)
  ; RTYPE T0 T3 T4 RISCV_SUB   (* sub	T4, T3, T0 *)
  ; RTYPE T0 T3 T3 RISCV_XOR   (* xor	T3, T3, T0 *)
  ; RTYPE T0 T4 T5 RISCV_XOR   (* xor	T5, T4, T0 *)
  ; RTYPE T3 T5 T3 RISCV_AND   (* and	T3, T5, T3 *)
  ; RTYPE T4 T3 T3 RISCV_XOR   (* xor	T3, T3, T4 *)
  ; ITYPE (bv.of_Z (-1)) T3 T3 RISCV_XORI   (* not	T3, T3 *)
  ; SHIFTIOP (bv.of_Z 31) T3 T3 RISCV_SRLI   (* srli	T3, T3, 31 *)
  ; RTYPE T1 T2 T1 RISCV_OR   (* or	T1, T2, T1 *)
  ; RTYPE T3 T1 T1 RISCV_OR   (* or	T1, T1, T3 *)
  ; RTYPE T0 A7 A7 RISCV_XOR   (* xor	A7, A7, T0 *)
  ; ITYPE (bv.of_Z 1) A7 T0 RISCV_SLTIU   (* seqz	T0, A7 *)
  ; ITYPE (bv.of_Z 1) T1 T2 RISCV_SLTIU   (* seqz	T2, T1 *)
  ; ITYPE (bv.of_Z 4) A2 A7 RISCV_ADDI   (* addi	A7, A2, 4 *)
  ; ITYPE (bv.of_Z (-1)) T2 T2 RISCV_ADDI   (* addi	T2, T2, -1 *)
  ; ITYPE (bv.of_Z (-1)) T1 T1 RISCV_ADDI   (* addi	T1, T1, -1 *)
  ; RTYPE T1 T2 T1 RISCV_AND   (* and	T1, T2, T1 *)
  ; RTYPE A3 T1 T2 RISCV_XOR   (* xor	T2, T1, A3 *)
  ; RTYPE T0 X0 T0 RISCV_SUB   (* neg	T0, T0 *)
  ; RTYPE T0 T2 T0 RISCV_AND   (* and	T0, T2, T0 *)
  ; RTYPE T1 T0 T0 RISCV_XOR   (* xor	T0, T0, T1 *)
  ; RTYPE A5 A1 T1 RISCV_ADD   (* add	T1, A1, A5 *)
  ; ITYPE (bv.of_Z 1) X0 A5 RISCV_ADDI   (* li	A5, 1 *)
  ; LOAD (bv.of_Z 0) A7 T2 false WORD   (* lw	T2, 0(A7) *)
  ; MULHU T3 T2 T0   (* mulhu	T3, T2, T0 -- fixed from asm_to_ast.py's raw Base.MUL form to Spec.v's Assembly.MULHU (rd rs1 rs2) smart constructor *)
  ; MUL T4 T2 T0   (* mul	T4, T2, T0 -- fixed from asm_to_ast.py's raw Base.MUL form to Spec.v's Assembly.MUL (rd rs1 rs2) smart constructor *)
  ; RTYPE A6 T4 A6 RISCV_ADD   (* add	A6, T4, A6 *)
  ; RTYPE T4 A6 T4 RISCV_SLTU   (* sltu	T4, A6, T4 *)
  ; RTYPE T4 T3 T3 RISCV_ADD   (* add	T3, T3, T4 *)
  ; SHIFTIOP (bv.of_Z 1) T3 T3 RISCV_SLLI   (* slli	T3, T3, 1 *)
  ; LOAD (bv.of_Z 0) A1 T4 false WORD   (* lw	T4, 0(A1) *)
  ; SHIFTIOP (bv.of_Z 31) A6 T5 RISCV_SRLI   (* srli	T5, A6, 31 *)
  ; RTYPE T3 T5 T3 RISCV_OR   (* or	T3, T5, T3 *)
  ; RTYPE A3 A6 A6 RISCV_AND   (* and	A6, A6, A3 *)
  ; RTYPE A6 T4 T4 RISCV_SUB   (* sub	T4, T4, A6 *)
  ; SHIFTIOP (bv.of_Z 31) T4 A6 RISCV_SRLI   (* srli	A6, T4, 31 *)
  ; RTYPE T3 A6 A6 RISCV_ADD   (* add	A6, A6, T3 *)
  ; RTYPE A3 T4 T3 RISCV_AND   (* and	T3, T4, A3 *)
  ; STORE (bv.of_Z 0) T3 A1 WORD   (* sw	T3, 0(A1) *)
  ; RTYPE T3 T2 T4 RISCV_XOR   (* xor	T4, T2, T3 *)
  ; ITYPE (bv.of_Z 1) T4 T4 RISCV_SLTIU   (* seqz	T4, T4 *)
  ; RTYPE T3 T2 T3 RISCV_SUB   (* sub	T3, T2, T3 *)
  ; ITYPE (bv.of_Z (-1)) T2 T2 RISCV_XORI   (* not	T2, T2 *)
  ; RTYPE T2 T3 T2 RISCV_AND   (* and	T2, T3, T2 *)
  ; SHIFTIOP (bv.of_Z 31) T2 T2 RISCV_SRLI   (* srli	T2, T2, 31 *)
  ; RTYPE T4 X0 T3 RISCV_SUB   (* neg	T3, T4 *)
  ; RTYPE A5 T2 A5 RISCV_XOR   (* xor	A5, T2, A5 *)
  ; RTYPE T3 A5 A5 RISCV_AND   (* and	A5, A5, T3 *)
  ; RTYPE T2 A5 A5 RISCV_XOR   (* xor	A5, A5, T2 *)
  ; ITYPE (bv.of_Z 4) A1 A1 RISCV_ADDI   (* addi	A1, A1, 4 *)
  ; ITYPE (bv.of_Z 4) A7 A7 RISCV_ADDI   (* addi	A7, A7, 4 *)
  ; BTYPE (bv.of_Z (-112)) T1 A1 RISCV_BNE   (* bne	A1, T1, .LBB3_20 *)
  ; RTYPE A6 A4 A7 RISCV_SUB   (* sub	A7, A4, A6 *)
  ; RTYPE A4 A6 A1 RISCV_XOR   (* xor	A1, A6, A4 *)
  ; RTYPE A6 A7 T0 RISCV_XOR   (* xor	T0, A7, A6 *)
  ; LOAD (bv.of_Z 0) A0 T1 false WORD   (* lw	T1, 0(A0) *)
  ; RTYPE A1 T0 T0 RISCV_AND   (* and	T0, T0, A1 *)
  ; RTYPE A7 T0 A7 RISCV_XOR   (* xor	A7, T0, A7 *)
  ; SHIFTIOP (bv.of_Z 31) A7 T0 RISCV_SRLI   (* srli	T0, A7, 31 *)
  ; ITYPE (bv.of_Z 63) T1 T1 RISCV_ADDI   (* addi	T1, T1, 63 *)
  ; SHIFTIOP (bv.of_Z 5) T1 A7 RISCV_SRLI   (* srli	A7, T1, 5 *)
  ; ITYPE (bv.of_Z 64) X0 T2 RISCV_ADDI   (* li	T2, 64 *)
  ; SHIFTIOP (bv.of_Z 2) A7 A7 RISCV_SLLI   (* slli	A7, A7, 2 *)
  ; BTYPE (bv.of_Z 80) T2 T1 RISCV_BLTU   (* bltu	T1, T2, .LBB3_24 *)
  ; ITYPE (bv.of_Z 0) X0 T3 RISCV_ADDI   (* li	T3, 0 *)
  ; ITYPE (bv.of_Z 0) T0 T4 RISCV_ADDI   (* mv	T4, T0 *)
  ; RTYPE T4 X0 T4 RISCV_SUB   (* neg	T4, T4 *)
  ; ITYPE (bv.of_Z 4) A2 T5 RISCV_ADDI   (* addi	T5, A2, 4 *)
  ; ITYPE (bv.of_Z 4) A0 T6 RISCV_ADDI   (* addi	T6, A0, 4 *)
  ; RTYPE A7 A2 S0 RISCV_ADD   (* add	S0, A2, A7 *)
  ; LOAD (bv.of_Z 0) T6 S1 false WORD   (* lw	S1, 0(T6) *)
  ; LOAD (bv.of_Z 0) T5 S2 false WORD   (* lw	S2, 0(T5) *)
  ; RTYPE T3 S1 T3 RISCV_ADD   (* add	T3, S1, T3 *)
  ; RTYPE S2 T3 S2 RISCV_ADD   (* add	S2, T3, S2 *)
  ; SHIFTIOP (bv.of_Z 31) S2 T3 RISCV_SRLI   (* srli	T3, S2, 31 *)
  ; RTYPE A3 S2 S2 RISCV_AND   (* and	S2, S2, A3 *)
  ; RTYPE S1 S2 S2 RISCV_XOR   (* xor	S2, S2, S1 *)
  ; RTYPE T4 S2 S2 RISCV_AND   (* and	S2, S2, T4 *)
  ; RTYPE S1 S2 S1 RISCV_XOR   (* xor	S1, S2, S1 *)
  ; STORE (bv.of_Z 0) S1 T6 WORD   (* sw	S1, 0(T6) *)
  ; ITYPE (bv.of_Z 4) T5 T5 RISCV_ADDI   (* addi	T5, T5, 4 *)
  ; ITYPE (bv.of_Z 4) T6 T6 RISCV_ADDI   (* addi	T6, T6, 4 *)
  ; BTYPE (bv.of_Z (-48)) S0 T5 RISCV_BNE   (* bne	T5, S0, .LBB3_23 *)
  ; BTYPE (bv.of_Z 108) T2 T1 RISCV_BLTU   (* bltu	T1, T2, .LBB3_27 *)
  ; ITYPE (bv.of_Z 0) X0 T1 RISCV_ADDI   (* li	T1, 0 *)
  ; RTYPE A4 A6 A6 RISCV_SUB   (* sub	A6, A6, A4 *)
  ; RTYPE A4 A6 A4 RISCV_XOR   (* xor	A4, A6, A4 *)
  ; RTYPE A1 A4 A1 RISCV_AND   (* and	A1, A4, A1 *)
  ; RTYPE A6 A1 A1 RISCV_XOR   (* xor	A1, A1, A6 *)
  ; SHIFTIOP (bv.of_Z 31) A1 A1 RISCV_SRLI   (* srli	A1, A1, 31 *)
  ; ITYPE (bv.of_Z (-1)) T0 A4 RISCV_XORI   (* not	A4, T0 *)
  ; RTYPE A5 A1 A1 RISCV_OR   (* or	A1, A1, A5 *)
  ; RTYPE A4 A1 A1 RISCV_AND   (* and	A1, A1, A4 *)
  ; RTYPE A1 X0 A1 RISCV_SUB   (* neg	A1, A1 *)
  ; ITYPE (bv.of_Z 4) A2 A4 RISCV_ADDI   (* addi	A4, A2, 4 *)
  ; ITYPE (bv.of_Z 4) A0 A0 RISCV_ADDI   (* addi	A0, A0, 4 *)
  ; RTYPE A7 A2 A2 RISCV_ADD   (* add	A2, A2, A7 *)
  ; LOAD (bv.of_Z 0) A0 A5 false WORD   (* lw	A5, 0(A0) *)
  ; LOAD (bv.of_Z 0) A4 A6 false WORD   (* lw	A6, 0(A4) *)
  ; RTYPE T1 A5 T1 RISCV_ADD   (* add	T1, A5, T1 *)
  ; RTYPE A6 T1 A6 RISCV_SUB   (* sub	A6, T1, A6 *)
  ; SHIFTIOP (bv.of_Z 31) A6 T1 RISCV_SRAI   (* srai	T1, A6, 31 *)
  ; RTYPE A3 A6 A6 RISCV_AND   (* and	A6, A6, A3 *)
  ; RTYPE A5 A6 A6 RISCV_XOR   (* xor	A6, A6, A5 *)
  ; RTYPE A1 A6 A6 RISCV_AND   (* and	A6, A6, A1 *)
  ; RTYPE A5 A6 A5 RISCV_XOR   (* xor	A5, A6, A5 *)
  ; STORE (bv.of_Z 0) A5 A0 WORD   (* sw	A5, 0(A0) *)
  ; ITYPE (bv.of_Z 4) A4 A4 RISCV_ADDI   (* addi	A4, A4, 4 *)
  ; ITYPE (bv.of_Z 4) A0 A0 RISCV_ADDI   (* addi	A0, A0, 4 *)
  ; BTYPE (bv.of_Z (-48)) A2 A4 RISCV_BNE   (* bne	A4, A2, .LBB3_26 *)
  ; LOAD (bv.of_Z 12) X2 S0 false WORD   (* lw	S0, 12(X2)                      # 4-byte Folded Reload *)
  ; LOAD (bv.of_Z 8) X2 S1 false WORD   (* lw	S1, 8(X2)                       # 4-byte Folded Reload *)
  ; LOAD (bv.of_Z 4) X2 S2 false WORD   (* lw	S2, 4(X2)                       # 4-byte Folded Reload *)
  ; LOAD (bv.of_Z 0) X2 S3 false WORD   (* lw	S3, 0(X2)                       # 4-byte Folded Reload *)
  ; ITYPE (bv.of_Z 16) X2 X2 RISCV_ADDI   (* addi	X2, X2, 16 *)
  ].

(* A0=&x[0], A1=z (SECRET scalar being folded in), A2=&m[0], X2=sp (initial,
   pre-decrement). A3-A7/T0-T6/S0-S3 are all write-before-read scratch on
   the live path (X1/ra is used ONLY inside the provably-dead early-return
   block, so -- like ZZCheckScalarFullN2.v's own X1 -- it needs no entry
   here at all). *)
Definition zzmuladdfulln2_reg_specs_rel : list reg_spec_rel :=
  [ (A0, true,  PVBaseOff 1128)
  ; (A1, false, PVExist)
  ; (A2, true,  PVBaseOff 1140)
  ; (X2, true,  PVBaseOff 1168)
  ; (A3, false, PVExist); (A4, false, PVExist); (A5, false, PVExist)
  ; (A6, false, PVExist); (A7, false, PVExist)
  ; (T0, false, PVExist); (T1, false, PVExist); (T2, false, PVExist)
  ; (T3, false, PVExist); (T4, false, PVExist); (T5, false, PVExist)
  ; (T6, false, PVExist)
  ; (S0, false, PVExist); (S1, false, PVExist); (S2, false, PVExist)
  ; (S3, false, PVExist)
  ].

(* x[]: x[0]=bitlen PINNED 63 (PUBLIC, matches m[0] -- see header comment);
   x[1],x[2] SECRET, existentially quantified (the value being reduced). *)
Definition zzmuladdfulln2_x_specs_rel : list mem_spec_rel :=
  [ (1128%N, true,  PVConst (bv.of_N 63))
  ; (1132%N, false, PVExist)
  ; (1136%N, false, PVExist)
  ].

(* m[]: m[0]=bitlen PINNED 63 (PUBLIC); m[1],m[2] PUBLIC-but-unpinned. *)
Definition zzmuladdfulln2_m_specs_rel : list mem_spec_rel :=
  [ (1140%N, true, PVConst (bv.of_N 63))
  ; (1144%N, true, PVExist)
  ; (1148%N, true, PVExist)
  ].

(* Stack spill slots for S0-S3 (save/restore only, never branched on). *)
Definition zzmuladdfulln2_stack_specs_rel : list mem_spec_rel :=
  [ (1152%N, false, PVExist); (1156%N, false, PVExist)
  ; (1160%N, false, PVExist); (1164%N, false, PVExist)
  ].

Definition zzmuladdfulln2_mem_specs_rel : list mem_spec_rel :=
  zzmuladdfulln2_x_specs_rel ++ zzmuladdfulln2_m_specs_rel
  ++ zzmuladdfulln2_stack_specs_rel.

(* Bound 1168: one past the last declared word (the stack region ends at
   1164+4=1168). Fuel 500: generous slack -- per cfgver-executor, fuel is
   nearly free (4.4x fuel cost +0.04% allocation), so no need to tune tight;
   tight fuel would surface as a bare False deep in the VC. *)
Definition zzmuladdfulln2_cfg_contract_param (ia : N)
    : @CFGVerifierContract ["p" :: ty_xlenbits] :=
  gen_contract_rel ia zzmuladdfulln2_reg_specs_rel zzmuladdfulln2_mem_specs_rel
    zzmuladdfulln2_instrs [] 1168%N
    (pcOutOfInstrs_exitCond ia zzmuladdfulln2_instrs) 500.

Lemma valid_zzmuladdfulln2_cfg_contract_param (ia : N) :
  ValidCFGVerifierContract (zzmuladdfulln2_cfg_contract_param ia).
Proof. intros; vm_compute; solve_vc; solve_symbase_fetch. Qed.
