#!/usr/bin/env bash
# scripts/install-hooks.sh — install the local git hooks for this repo.
#
# .git/hooks is NOT tracked by git, so it does not survive a fresh clone. Run this
# once after cloning (and again if the hook wrapper below changes) to wire the
# merge gate into `git merge`.
#
#   ./scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK="$REPO_ROOT/.git/hooks/pre-merge-commit"

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# AUTO-GENERATED by scripts/install-hooks.sh — do not edit here.
# Edit the gate logic in scripts/gate.sh instead.
#
# Fires before a merge COMMIT is created (git merge without a fast-forward).
# Runs the merge gate only when merging into a protected branch, so merges into
# short-lived feature branches stay fast.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"
branch="$(git symbolic-ref --short HEAD 2>/dev/null || echo '')"
PROTECTED="main KatamaranRel"
case " $PROTECTED " in
  *" $branch "*) ;;      # protected → run the gate
  *) exit 0 ;;           # anything else → skip
esac
echo "⛲ pre-merge-commit: running merge gate for '$branch'…"
exec "$REPO_ROOT/scripts/gate.sh"
EOF

chmod +x "$HOOK"
echo "Installed hook: $HOOK"
echo "Protected branches: main KatamaranRel (edit inside the hook / scripts/gate.sh to change)."
